### ISSUE TITLE
Allow more history to be stored?

### ISSUE THREAD

**Issue by VestigiaLunae** [p0deje/Maccy#657] opened 2023-10-25 15:29 UTC
I tried out other copy-paste apps, like Copy clip 2(only trial). They seemed to support unlimited history by storing it in sql files, and also used less memory. I'm not sure if that kind of approach will be possible but I would love to have more items stored in history.

**Comment by p0deje** [comment] 2023-10-25 17:06
Duplicate of #310

**Closed by p0deje** 2023-10-25 17:06 UTC
