### ISSUE TITLE
Maccy not launching on login, though that preference is set

### ISSUE THREAD

**Issue by pbx-lcvista** [p0deje/Maccy#683] opened 2023-11-30 20:56 UTC
## Environment
* Maccy version `0.28.0 (23)`
* macOS 14.1.2 (on M2)

## Repro 
1. Turn on "Launch at login" in Maccy general prefs
2. Reboot
3. Note that Maccy has not launched

No relevant crash logging in Console.app that I can see.

**Comment by p0deje** [comment] 2023-12-01 15:22
> I notice that it’s listed with a generic document icon (that may be normal but mentioning it in  case it’s a clue).

Yes, this looks strange. Can you try reinstalling Maccy?

**Comment by p0deje** [comment] 2023-12-03 00:33
@pbx-lcvista Can you try removing all version of Maccy and install the latest 0.29?

**Comment by TommyYOyoyo** [comment] 2024-01-12 02:20
Hello, I have the same issue here. The Maccy on my device has the latest version (0.29.3), and both the launch at login preference of Maccy and login items checkbox are selected. I'm on a macOS 14.1.2 on an intel MacBook Air 2020.

**Comment by p0deje** [comment] 2024-01-12 16:04
@TommyYOyoyo Can you please check the same as in https://github.com/p0deje/Maccy/issues/683#issuecomment-1834602534?

**Comment by TommyYOyoyo** [comment] 2024-01-13 20:43
> @TommyYOyoyo Can you please check the same as in [#683 (comment)](https://github.com/p0deje/Maccy/issues/683#issuecomment-1834602534)?

Yep, Maccy is effectively added into the "open at login" section as shown in this picture.

<img width="472" alt="image" src="https://github.com/p0deje/Maccy/assets/79941840/15f788ca-919e-43a8-a028-650c0441bb75">

**Comment by p0deje** [comment] 2024-01-14 22:37
Yeah, looks strange at least because there is no Maccy icon. Can you double-check you don't have any other versions of Maccy installed? Then re-install, remove Maccy from "Login items" manually, and try again.

**Comment by TommyYOyoyo** [comment] 2024-01-17 21:39
> Yeah, looks strange at least because there is no Maccy icon. Can you double-check you don't have any other versions of Maccy installed? Then re-install, remove Maccy from "Login items" manually, and try again.

Yep, indeed. I've double-checked and this is the only version of Maccy that I have. I've also tried to remove and manually put back Maccy in login items, it unfortunately didn't work either :(

**Comment by p0deje** [comment] 2024-01-17 21:54
@TommyYOyoyo I am not sure where to go from there. Please try uninstalling Maccy, removing the login item and then installing the most recent version.

**Comment by TommyYOyoyo** [comment] 2024-01-18 21:32
> @TommyYOyoyo I am not sure where to go from there. Please try uninstalling Maccy, removing the login item and then installing the most recent version.

That worked! Thank you very much!!!

**Comment by p0deje** [comment] 2024-01-22 22:32
I am going to close this for now since I cannot find a way to reproduce and debug the issue. Please re-open with extra details if happens again.

**Closed by p0deje** 2024-01-22 22:32 UTC
