### ISSUE TITLE
Add a switch between All, Texts, Images and Files

### ISSUE THREAD

**Issue by free-storage** [p0deje/Maccy#526] opened 2023-03-15 15:01 UTC
Hi. It will be convenient if you add a switch between All, Texts, Images and Files. You open the window, switch and can filter only pictures, for example. It would be very convenient.

**Comment by p0deje** [comment] 2023-03-15 17:17
Duplicate of #360

**Comment by p0deje** [comment] 2023-03-15 17:17
Sorry, it's #206

**Closed by p0deje** 2023-03-15 17:17 UTC

**Comment by free-storage** [comment] 2023-03-15 20:49
@p0deje Thank you. I'm waiting for an update.
