### ISSUE TITLE
`cmd+,` with footer hidden no longer works(macOS Sonoma developer beta)

### ISSUE THREAD

**Issue by Meadowsys** [p0deje/Maccy#556] opened 2023-06-07 08:30 UTC
I noticed when I turn off the footer I cannot `cmd+,` to bring up the preferences, and had to run `defaults write org.p0deje.Maccy hideFooter 0` to reset the seting, then restart Maccy for it to work. This only happened after I updated to Sonoma developer beta, alongside another issue (#555), so as I wrote there I don't think this is of high priority at the moment, until Sonoma stabilises.

**Comment by p0deje** [comment] 2023-06-28 18:48
The issue is the same as #555 - event processing doesn't work. Closing this as duplicate.

**Closed by p0deje** 2023-06-28 18:48 UTC
Labels: bug, needs triaging
