### ISSUE TITLE
Maccy does not open with "Option" in appearence keymap

### ISSUE THREAD

**Issue by serjb9** [p0deje/Maccy#896] opened 2024-09-24 09:51 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.1

### macOS Version

15.0

### Maccy Settings

```Shell
❯ defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":8,\\"carbonModifiers\\":2560}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 5650;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUStatusFrame" = "664 724 400 134 0 0 1728 1079 ";
    "NSWindow Frame SUUpdateAlert" = "527 510 620 398 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "593 379 542 435 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "582 467 510 473 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-24 09:46:43 +0000";
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.html",
        "public.rtf",
        "public.tiff",
        "public.png",
        "public.utf8-plain-text"
    );
    historySize = 500;
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "net.antelle.keeweb"
    );
    maxMenuItemLength = 50;
    maxMenuItems = 20;
    menuIcon = maccy;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    popupPosition = center;
    popupScreen = 0;
    previewDelay = 500;
    showFooter = 1;
    showSearch = 1;
    showTitle = 1;
    windowSize = "[450,800]";
}
```

### Description

After upgrade, if hotkey consist with "Option" button, the appearence action does not work.
My current keymap - SHIFT + OPTION + C
I've tried reinstall and with default keymap it does work.

Switching back to deafult keymap - SHIFT + CMD + C - it does work

### Steps to Reproduce

1. Open settings - General
2. Set setting OPEN - SHIFT + OPTION + C
3. Close the window
4. Try to open Maccy using keymap SHIFT + OPTION + C

**Comment by p0deje** [comment] 2024-09-24 13:48
Duplicate of #813

**Closed by p0deje** 2024-09-24 13:48 UTC
Labels: bug
