### ISSUE TITLE
Snippets support

### ISSUE THREAD

**Issue by vandreykiv** [p0deje/Maccy#215] opened 2020-12-02 05:55 UTC
Hello,

I'm trying to switch from Clipy and only one thing I missed is snippets. It's kind of pinned items but I would ask if you can add folders and hide content inside item with possibility to set name. 

Thanks.

**Comment by p0deje** [comment] 2020-12-07 13:34
Duplicate of #89

**Closed by p0deje** 2020-12-07 13:34 UTC
