### ISSUE TITLE
auto delete after T time 

### ISSUE THREAD

**Issue by avichou** [p0deje/Maccy#558] opened 2023-06-08 20:37 UTC
could you implement an auto deletion feature , that would automatically delete all the clipboard history after T time ? 

thanks !

**Comment by p0deje** [comment] 2023-06-08 23:07
What's the use case for that? Can you please explain how would you benefit from having this feature?

**Comment by avichou** [comment] 2023-06-11 23:25
> What's the use case for that? Can you please explain how would you benefit from having this feature?

oh gosh,sorry for the late answer 

maybe don't bother since my request didn't get any upvote haha

but i'm a bit OCD and i like to unclutter my clipboard from time to time, especially when there are clipped images 

content usually becomes unecessary after i'm finished with my session, and it becomes irrelevant after that

**Comment by mehapps** [comment] 2023-06-14 23:47
I would 100% use this, I'd like to have no limit for clipboard items but instead clear after a week etc.

**Comment by p0deje** [comment] 2023-06-15 04:24
I think it would be nice to have it, but first #310 needs to be done.

**Comment by avichou** [comment] 2023-06-15 18:31
> I think it would be nice to have it, but first #310 needs to be done.

Because it's of higher importance, or because the two are related ? 

Anyway take your time , and i don't remember if I wrote to you about this already but : thank you so much for making such an amazing and beautiful app that palliates macOS lackluster clipboard management

**Comment by p0deje** [comment] 2023-06-15 20:22
> Because it's of higher importance, or because the two are related ?

Because in order to have an unlimited history (even for certain time period0, I need to figure out the memory problems.

> thank you so much for making such an amazing and beautiful app that palliates macOS lackluster clipboard management

Thank you, I appreciate your words.

**Comment by avichou** [comment] 2023-06-15 23:26
> > Because it's of higher importance, or because the two are related ?
> 
> Because in order to have an unlimited history (even for certain time period0, I need to figure out the memory problems.
> 
> > thank you so much for making such an amazing and beautiful app that palliates macOS lackluster clipboard management
> 
> Thank you, I appreciate your words.

I understand, good luck , and no hurries !

you're welcome , this truly is an amazing app. I'll send you money when I start working hopefully :)

**Comment by Pizzasteve67** [comment] 2023-06-29 13:38
Yes I would love this feature as well.
Use case is, most of the important pins that I need all the time I pin. But there are maybe 5-10 copies that I only need for a short session that I may forget to clear. These arent important enough for me to pin and I wouldnt mind them being gone after 24 hours so as to not clutter my space. 
In terms of implementation can we have like a timer that clears all non pinned items after a set duration of time: 1hr, 1day, 1week.
I would use this feature everyday!!!

**Comment by p0deje** [comment] 2023-07-01 20:40
This is actually a duplicate of #368

**Closed by p0deje** 2023-07-01 20:40 UTC
Labels: enhancement
