### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kfirfer** [p0deje/Maccy#937] opened 2024-10-25 23:57 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.1.0 

### macOS Version

15.0.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":8,\\"carbonModifiers\\":768}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavLastRootDirectory = "/Applications";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Preferred Position Item-0" = 146;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "356 385 800 448 0 0 1512 944 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "539 537 510 232 0 0 1512 944 ";
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.tiff",
        "public.rtf",
        "public.png",
        "public.html"
    );
    historySize = 500;
    ignoredApps =     (
        "com.bitwarden.desktop",
        "com.1password.1password"
    );
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "Pasteboard generator type"
    );
    imageMaxHeight = 40;
    lastReviewRequestedAt = 1724261726;
    maxMenuItemLength = 50;
    maxMenuItems = 25;
    menuIcon = paperclip;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    numberOfUsages = 238;
    pinTo = top;
    popupPosition = cursor;
    previewDelay = 1500;
    searchMode = mixed;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showSpecialSymbols = 1;
    showTitle = 1;
    suppressClearAlert = 0;
    windowSize = "[450,800]";
}
```

### Description

Hello

The Memory usage of Maccy is huge (25GB):
<img width="886" alt="SCR-20241026-ihse-2" src="https://github.com/user-attachments/assets/7bf1ab32-44a9-4b5d-8a3b-fc8edc4803dc">

Even tho I cleared the history, the usage not moved anywhere

**Comment by GrayJack** [comment] 2024-11-02 20:09
I confirm this bug, I just killed maccy that was usiing 11 GB of RAM, and cleaning history had no effect

**Comment by rishi-singh26** [comment] 2024-11-04 13:47
I can also confirm this. 103 MB RAM is being used, I just reinstalled the application and clipboard is empty.

![image](https://github.com/user-attachments/assets/b830658e-749f-49e1-bd57-7825a72489ca)

**Comment by aderk** [comment] 2024-11-14 23:15
+1

Maccy was using 1.2GiB of RAM after ~1week of uptime. When I restarted it (without clearing history), it is down to 39 MiB of memory usage.

**Comment by p0deje** [comment] 2024-11-24 05:23
Duplicate of #384

**Closed by p0deje** 2024-11-24 05:23 UTC
Labels: bug
