### ISSUE TITLE
Footer disabled - cannot access preferences

### ISSUE THREAD

**Issue by andraz-kozelj** [p0deje/Maccy#295] opened 2021-07-03 21:31 UTC
On Monterey beta2 I checked "hide footer" and now when I open the item list window (by clicking the menu icon or with a hotkey), pressing "command+," does nothing.
Adding a right-click menu on the menubar icon would work fantastically - add all footer options to right click!

Edit: just found out that when in search field, "cmd+," does nothing, but if I type anything in the search field, whether it finds a match or it filters everything off the list, "cmd+," works and displays the preferences window.

**Comment by rvdsteege** [comment] 2021-07-05 06:50
I'm experiencing the same on Monterey. This sounds related to/duplicate of the focus issue on Monterey as described in https://github.com/p0deje/Maccy/issues/287#issuecomment-872796951

**Comment by p0deje** [comment] 2021-07-05 13:48
There is an issue in Monterey. I've tried getting a VM to debug and fix it, but it didn't work for me. I cannot upgrade yet as I have work to do and I can't afford to break the workflow. I'll try upgrading on the weekend and then will investigate.

If anyone knows how to run Monterey in VirtualBox (or another free virtualization program) on Big Sur, please let me know.

**Comment by kidonng** [comment] 2021-07-05 23:51
> If anyone knows how to run Monterey in VirtualBox (or another free virtualization program) on Big Sur, please let me know.

According to https://kb.parallels.com/en/125506, there's less hassle if install Big Sur first and then upgrade.

**Comment by p0deje** [comment] 2021-07-07 01:20
Unfortunately I had no luck with upgrading from Big Sur to Monterey on VirtualBox. I don't have Parallels too.

**Comment by kidonng** [comment] 2021-07-07 02:03
You can try VMware fusion, which have free personal license.

**Comment by p0deje** [comment] 2021-07-10 21:34
Fixed in e559d57

**Closed by p0deje** 2021-07-10 21:34 UTC
Labels: bug
