### ISSUE TITLE
[Feature Request]: iCloud Sync for Maccy 

### ISSUE THREAD

**Issue by omar-hanafy** [p0deje/Maccy#592] opened 2023-07-29 14:14 UTC
Firstly, I want to express my appreciation for the outstanding work you've done with the Maccy app for Mac. It has become an essential tool for managing my clipboard history.

request the implementation of iCloud sync functionality for Maccy on Mac. Having the ability to sync clipboard history across multiple Mac devices through iCloud would greatly enhance the user experience and productivity and also provide a convenient backup mechanism, In the event of device loss, damage, or upgrade, users would be able to restore their clipboard history effortlessly.

**Comment by p0deje** [comment] 2023-08-12 16:35
Duplicate of #182, please see it.

**Closed by p0deje** 2023-08-12 16:35 UTC
