### ISSUE TITLE
Incorrect window is activated after Maccy is deactivated

### ISSUE THREAD

**Issue by Loskir** [p0deje/Maccy#404] opened 2022-05-13 16:01 UTC
Steps to reproduce:
1. Open two windows of the same app on different displays
2. Activate and deactivate Maccy while using the app on the second display
3. After deactivation, window on the first display gets activated instead of the window on the second display.

This does not happen with every application, I was able to get this behavior with Firefox and Webstorm.
The problem is not specific to Maccy, this also happens when you close an application and the previous one gets activated. Maybe that's due to the way Maccy behaves upon deactivation

**Comment by p0deje** [comment] 2022-06-03 15:59
I cannot reproduce this using Firefox and two displays. Could it be some other application that you use for window management?

**Comment by p0deje** [comment] 2022-07-31 21:44
Closing since no reply for more than a month.

**Closed by p0deje** 2022-07-31 21:44 UTC
Labels: bug, needs triaging
