### ISSUE TITLE
Works similar to [Ditto copy windows](https://ditto-cp.sourceforge.io/)

### ISSUE THREAD

**Issue by 7zism3** [p0deje/Maccy#706] opened 2024-01-13 18:44 UTC
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I am a new Windows user who switched to Mac OS.
At Windows I am familiar with the copy manager - "Diito copy". It's really great and satisfies me enough.
When switching to mac os. I have tried many apps but still haven't found an app like that. Maccy is amazing, it's almost perfect, just missing one thing:
When I click the shortcut that opens the copy records list (ctrl + /` ): the copy records list shows up
When I continue to hold the Ctrl key and press the ` key several times in quick succession: nothing happens. I would expect it to work the same as on Ditto - move on to the next copy record or there is an option like that. And when you release the ctrl key, the copied record is automatically pasted, instead of having to press enter if selecting the first record
Thank yous

### Solution

Works similar to [Ditto copy windows](https://ditto-cp.sourceforge.io/)
When I click the shortcut that opens the copy records list (ctrl + `): the copy records list shows up
When I continue to hold the Ctrl key and press the ` key several times in quick succession: nothing happens. I would expect it to work the same as on Ditto - move on to the next copy record or there is an option like that. And when you release the ctrl key, the copied record is automatically pasted, instead of having to press enter if selecting the first record

**Comment by p0deje** [comment] 2024-01-13 18:46
This is duplicate of #96

**Closed by p0deje** 2024-01-13 18:46 UTC
Labels: enhancement
