### ISSUE TITLE
Can I ask Maccy to ignore images completely? 

### ISSUE THREAD

**Issue by yashmishra12** [p0deje/Maccy#237] opened 2021-02-08 09:34 UTC
I don't want Maccy to store my screenshots. (cmd+ctrl+shift+4 and cmd+ctrl+shift+3). How do I ignore them? Can I ask Maccy to ignore images completely?

**Comment by p0deje** [comment] 2021-02-12 01:06
Duplicate of #134

**Closed by p0deje** 2021-02-12 01:06 UTC
