### ISSUE TITLE
macOS Sonoma support

### ISSUE THREAD

**Issue by Meadowsys** [p0deje/Maccy#555] opened 2023-06-07 08:30 UTC
Hi! I found out after installing the developer beta of macOS Sonoma (14.0), that I can no longer delete entries using `opt+delete`. As I press `opt` with Maccy focused, it hides all of my clipboard entries, except the footer if that's set to show. Releasing opt makes it all show up again.

There is another issue that popped up yesterday alongside this one (#556), so because these two issues came up at the same time and after I updated, I'm tempted to say it's a bug on macOS' side? Might be a good idea to wait for it to stabilise and see if it fixes itself.

**Comment by p0deje** [comment] 2023-06-07 11:44
I'll try installing the beta and seeing what can be fixed.

**Comment by jhaemin** [comment] 2023-06-16 08:31
Also the information popup doesn't appear when hovered on a history item.

**Comment by j-dogcoder** [comment] 2023-07-09 22:57
Also experiencing this...

**Comment by p0deje** [comment] 2023-08-05 21:34
I've raised two issues via Feedback Assistant hoping they will be fixed in newer beta:
- https://github.com/feedback-assistant/reports/issues/413
- https://github.com/feedback-assistant/reports/issues/412

**Comment by p0deje** [comment] 2023-08-07 21:58
Another one: https://github.com/feedback-assistant/reports/issues/414

**Comment by p0deje** [comment] 2023-08-12 16:14
Another one:
- https://github.com/feedback-assistant/reports/issues/415

**Comment by p0deje** [comment] 2023-08-12 16:33
If anyone is eager to try a prerelease version, you can download it from [Maccy.app.zip](https://github.com/p0deje/Maccy/files/12327821/Maccy.app.zip)

Here are the known issues:
1. Search-as-you-type works now. However, the whole menu is actually messed up after searching, so make sure to disable **Show footer** in Appearance. Once disabled, you can still open preferences with `COMMAND+,`. It would still show plenty of glitches in the menu rendering but should be a bit better. Due to the same issues, (un)pinning and removing items cause visual issues.
2. Automatic selection of the first menu item doesn't work, so you have to press the down arrow to select it.
3. Preview is positioned in the center of the menu, not next to the selected menu item.

Please post any other issues related to Sonoma as comments here.

**Comment by aljustiet** [comment] 2023-08-12 19:03
> If anyone is eager to try a prerelease version, you can download it from [Maccy.app.zip](https://github.com/p0deje/Maccy/files/12327821/Maccy.app.zip)
> 
> Here are the known issues:
> 
> 1. Search-as-you-type works now. However, the whole menu is actually messed up after searching, so make sure to disable **Show footer** in Appearance. Once disabled, you can still open preferences with `COMMAND+,`. It would still show plenty of glitches in the menu rendering but should be a bit better. Due to the same issues, (un)pinning and removing items cause visual issues.
> 2. Automatic selection of the first menu item doesn't work, so you have to press the down arrow to select it.
> 3. Preview is positioned in the center of the menu, not next to the selected menu item.
> 
> Please post any other issues related to Sonoma as comments here.

Now I can pin and unpin

**Comment by aljustiet** [comment] 2023-08-12 19:10
> If anyone is eager to try a prerelease version, you can download it from [Maccy.app.zip](https://github.com/p0deje/Maccy/files/12327821/Maccy.app.zip)
> 
> Here are the known issues:
> 
> 1. Search-as-you-type works now. However, the whole menu is actually messed up after searching, so make sure to disable **Show footer** in Appearance. Once disabled, you can still open preferences with `COMMAND+,`. It would still show plenty of glitches in the menu rendering but should be a bit better. Due to the same issues, (un)pinning and removing items cause visual issues.
> 2. Automatic selection of the first menu item doesn't work, so you have to press the down arrow to select it.
> 3. Preview is positioned in the center of the menu, not next to the selected menu item.
> 
> Please post any other issues related to Sonoma as comments here.

With two screens it appears only on external display when using Command+Shift+J ( I use Dvorak layout)

**Comment by MaximIgenbergs** [comment] 2023-08-19 11:55
@p0deje Sorry if I misinterpreted your message, but for me unpinning and removing pins still doesnt work. This is only fyi (MacOS Sonoma)

**Comment by p0deje** [comment] 2023-08-19 17:54
@MaximIgenbergs Did you try the version from https://github.com/p0deje/Maccy/issues/555#issuecomment-1675993191? It works fine for me on Developer Beta 4.

**Comment by Write** [comment] 2023-08-21 18:08
> @MaximIgenbergs Did you try the version from [#555 (comment)](https://github.com/p0deje/Maccy/issues/555#issuecomment-1675993191)? It works fine for me on Developer Beta 4.

I use the version above on macOS Sonoma Beta 5 and it does nothing ? I can't pin / unpin with keyboard shortcuts weirdly ?

**Comment by p0deje** [comment] 2023-09-01 19:30
Also raised the problems on Apple Developer forums - https://developer.apple.com/forums//thread/736721?answerId=763540022#763540022

**Comment by abrattic** [comment] 2023-09-02 05:28
I don't know why but Option P does not work for me to pin items 😕

**Comment by MaximIgenbergs** [comment] 2023-09-03 13:45
@p0deje version from https://github.com/p0deje/Maccy/issues/555#issuecomment-1675993191 works fine. thanks :)

**Comment by j-dogcoder** [comment] 2023-09-03 13:46
I am on latest from brew, and I don't have pins

**Comment by Write** [comment] 2023-09-03 13:47
> I am on latest from brew, and I don't have pins

Please read the issue correctly, it's stated how to fix it.

**Comment by samtsevich** [comment] 2023-09-13 14:30
One more bug-related note: 
Now in the Finder and Safari the combination "Cmd+Shift+C" responds to "Go to your Computer folder" and "Start Element selection", respectively. 
Seems like, it is better to set another combination for the Maccy call in the next releases (no suggestion yet).
If you have any – please, leave a comment, developers will appreciate it. But also check whether this combination is not already in use in standard Apple apps

**Comment by notcgi** [comment] 2023-09-13 14:34
> If you have any – please, leave a comment

I use Cmd+Option+C. Have no problem and its comfortable to press with two fingers

**Comment by notcgi** [comment] 2023-09-13 14:39
Also version from https://github.com/p0deje/Maccy/issues/555#issuecomment-1675993191 works fine with new RC1

**Comment by samtsevich** [comment] 2023-09-18 09:19
One more bug was found on MacOS Sonoma (23A339):

And when I try the following steps, Maccy does not respond anymore.

1. Run Cmd-Option-C (my hotkey for the application window) 
2. Select some field I would like to delete
3. Run Option-Delete. The item is deleted now.
4. Immediately run again Option-Delete without selection of any element.
5. Now, the hotkey does not work, I can only now use Maccy from the Menu Bar, not by hotkey.

**Comment by p0deje** [comment] 2023-09-22 16:18
[Maccy.app.zip](https://github.com/p0deje/Maccy/files/12702683/Maccy.app.zip)


Here is a newer build that hopefully fixes most problems:
1. Item selection now works in 99% of cases.
2. You can use the footer.
3. There should be no visual issues.
4. Delete is stable.

Known issues:
1. Weird selection and the header is hidden when no search results are found.

Please report any new issues in the thread. If none, I'll make a new official release on Monday.

**Comment by lookfirst** [comment] 2023-09-24 16:17
@p0deje confirmed on sonoma that this fixes a bunch of the pin issues i was having. thanks!

**Comment by t4k** [comment] 2023-09-28 23:46
My Sonoma issue is that Maccy won't paste with the Enter/Return key on a highlighted item.

I can invoke Maccy with my hotkey or from the menu icon and ⌘ 1 is highlighted, and I can arrow up and down the list, but when I press `return` no paste happens. Pressing `⌘ 1` does not paste either.

If I enable _Paste automatically_ in Preferences, pressing `return` causes an audible beep but no paste. In this case pressing `⌘ 1` does, in fact, paste.

I've tried pasting into different applications, such as VS Code, Terminal, and this comment field on GitHub using Firefox.

I'm using the latest version from homebrew [0.27.1 (22)].

**Comment by p0deje** [comment] 2023-09-29 00:54
@t4k
1. Is this something you see only on Sonoma or before too?
2. Can you try removing and re-adding Maccy in System Settings -> Privacy & Security -> Accessibility? 
3. What keyboard layout do you use?

**Comment by t4k** [comment] 2023-09-29 01:22
@p0deje

1. I was using Maccy on a Ventura machine and never noticed this issue.
2. Removing and re-adding to Privacy & Security -> Accessibility did not change anything. (I also have Maccy added under Developer Tools.)
3. I use a US English QWERTY keyboard layout.

Other data points:

4. One machine I upgraded today was previously on Ventura and I upgraded in-place with an existing version of Maccy installed [0.26.5 (20)]. That version works as expected (though, as some have pointed out elsewhere in the issues, I am not seeing ⌘ 1 highlighted and I have to arrow down to select, which I don't mind).
5. On another machine I installed Sonoma fresh on a new volume and I am seeing the behavior that I initially reported.

**Comment by p0deje** [comment] 2023-09-29 01:35
@t4k Can you please record a full-screen video of the problem? I have an idea what it might be related to, but the fact that it works with ⌘1 but not Return is very confusing - both use the same mechanism to paste. In any event, the video might be helpful.

Also, can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by t4k** [comment] 2023-09-29 03:43
first click in each attempt was `return`, second was with `⌘ 1`: https://streamable.com/wd7zou

```
% defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":2304}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame SUStatusFrame" = "760 691 400 134 0 0 1920 1055 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "2369 245 542 436 1920 0 1440 875 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-09-28 21:17:18 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 688996260;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.file-url",
        "public.utf8-plain-text",
        "public.png",
        "public.html",
        "public.tiff"
    );
    historySize = 200;
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "net.antelle.keeweb"
    );
    maxMenuItems = 10;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 0;
}
```

I did notice one strange thing that is hard to reproduce: when I quit and start the app over again it seems like the first time I invoke with the hotkey and just press `return` I get the first item pasted, but if I change the selection with the arrow keys it won't work anymore, even upon subsequent invocations. I also tried changing my setting for _Keyboard navigation_ in System Settings (I typically have it enabled), which seemed to change the behavior some, but also hard to reproduce a pattern.

**Comment by p0deje** [comment] 2023-09-29 14:29
> first click in each attempt was return, second was with ⌘ 1: https://streamable.com/wd7zou

The first attempt looks broken indeed. Later, when you disable "Paste automatically", you should not expect the paste to happen and you should press OPTION+RETURN for the paste to happen.

**Comment by kelsensantos** [comment] 2023-10-09 20:15
> Hello,
> 
> Since I upgraded my computer to macOS Sonoma I can't open Maccy's preferences. I originally wanted to check if everything is alright because I can't add any more items in Maccy when copying text.
> 
> I had the footer hidden and now the `⌘` + `,` shortcut don't work anymore.
> 
> Is there some things I could do to debug this? Thanks in advance!

I had the same issue.
Uninstalled and installed back straight from app store and it works fine now.

However, i got the same issue as @t4k (pasting not working with `enter`).

**Comment by p0deje** [comment] 2023-10-16 00:24
Now with #613 merged most of the issues are addressed, please create new issues separately for bugs.

**Closed by p0deje** 2023-10-16 00:24 UTC
Labels: bug

**Comment by olawalejuwonm** [comment] 2025-02-07 13:57
What's the recommended solution please?

**Comment by jaspermayone** [comment] 2025-02-07 14:01
@olawalejuwonm it works just fine on latest Sonoma!

**Comment by olawalejuwonm** [comment] 2025-02-07 14:20
> [@olawalejuwonm](https://github.com/olawalejuwonm) it works just fine on latest Sonoma!

I got the error Error: This software does not run on macOS versions older than Sonoma.

**Comment by jaspermayone** [comment] 2025-02-07 14:21
key word being **older**

**Comment by jaspermayone** [comment] 2025-02-07 14:21
it does not run on **OLDER** versions

**Comment by olawalejuwonm** [comment] 2025-02-07 14:22
> it does not run on **OLDER** versions

Any alternative?

**Comment by jaspermayone** [comment] 2025-02-07 14:23
An older version of maccy
