### ISSUE TITLE
option+V to open maccy doesnt work since 2.0

### ISSUE THREAD

**Issue by avichou** [p0deje/Maccy#872] opened 2024-09-17 00:37 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0

### macOS Version

15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":2304}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUStatusFrame" = "520 556 400 134 0 0 1440 875 ";
    "NSWindow Frame SUUpdateAlert" = "401 357 637 398 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "393 541 585 435 0 0 1920 1055 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "465 304 510 487 0 0 1440 875 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-16 19:06:38 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 167479513;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    clearOnQuit = 0;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.utf8-plain-text",
        "public.tiff",
        "public.html",
        "public.file-url",
        "public.png"
    );
    historySize = 100;
    ignoreEvents = 0;
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType"
    );
    imageMaxHeight = 66;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    popupPosition = cursor;
    popupScreen = 0;
    removeFormattingByDefault = 0;
    showFooter = 1;
    showInStatusBar = 0;
    showSearch = 1;
    showTitle = 1;
    suppressClearAlert = 1;
    windowSize = "[450,800]";
}
```

### Description

option+V shortcut doesnt work for opening maccy 

command+option+v does work . it seems the combination for option+v doesnt work anymore, which is quite a pity given how convenient it was to summon it that way .....

### Steps to Reproduce

change maccy open shortcut to option+v
input option+v 
maccy does not open

**Comment by AlanGalaxy** [comment] 2024-09-17 01:34
Also met with this, I'm currently in macOS Sequoia, I also tried 0.31 version, it does not work either.

**Comment by s235784** [comment] 2024-09-17 07:04
It seems that the macOS 15 update has broken this shortcut. Hopefully, there's a way to reuse it.

**Comment by p0deje** [comment] 2024-09-17 14:58
For now, there is nothing we can do - it's an Apple update in Sequoia. I can only suggest to report this issue to Apple - the more people complain to them, the higher chances are they will revert this decision.

Closing as duplicate of #813

**Closed by p0deje** 2024-09-17 14:58 UTC
Labels: bug

**Comment by AlanGalaxy** [comment] 2024-09-17 15:36
macOS 15 disabled all the shortcut with "opt + any letter", one way to solve is to change to "control + letter"

**Comment by p0deje** [comment] 2024-09-17 15:38
Yes, that’s the only way at the moment.

Best,
Alex

**Comment by abrarhamim4829** [comment] 2024-09-17 23:49
macOS 15 has disabled all shortcuts using “Option + any letter.” To fix this, follow these steps to restore your Maccy shortcut:

	1.	Go to System Settings > Keyboard > Keyboard Shortcuts > Modifier Keys.
	2.	Change the “Option” key to “Command” or another key of your choice.
	3.	Restart your Mac to apply the changes.

After this, your old Maccy hotkey will work just like before.

**Comment by OrenAman** [comment] 2024-09-18 09:23
if you use Karabiner so you can import this rule to map Left Option+V to Left Control+V 

```
{
    "description": "Map Left Option+V to Left Control+V",
    "manipulators": [
        {
            "from": {
                "key_code": "v",
                "modifiers": {
                    "mandatory": ["left_option"],
                    "optional": ["any"]
                }
            },
            "to": [
                {
                    "key_code": "v",
                    "modifiers": ["left_control"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by CoreJa** [comment] 2024-09-24 05:48
For anyone who uses karabiner and doesn't want to ruin their original modifiers(say you don't want to bind ctrl+v to maccy and just want to use option+v), here's a simpler rule:

```json
{
    "description": "maccy",
    "manipulators": [
        {
            "from": {
                "key_code": "v",
                "modifiers": { "mandatory": ["option"] }
            },
            "to": [{ "shell_command": "open -b org.p0deje.Maccy" }],
            "type": "basic"
        }
    ]
}
```

Here it doesn't bind to anything shortcut, instead it just calls maccy.app

**Comment by falahati** [comment] 2024-10-22 15:14
> macOS 15 disabled all the shortcut with "opt + any letter", one way to solve is to change to "control + letter"

Dont know if this is an exception, but Raycast's `option + space` still works.

**Comment by shichanglin5** [comment] 2024-11-09 01:09
> For now, there is nothing we can do - it's an Apple update in Sequoia. I can only suggest to report this issue to Apple - the more people complain to them, the higher chances are they will revert this decision.
> 
> Closing as duplicate of #813

Translation:

Why is CleanClip (another clipboard tool) able to use the Option+V shortcut normally?
<img width="715" alt="4E537C0C-C494-40E6-B670-C67BC4E40659" src="https://github.com/user-attachments/assets/57894c84-6e47-41ff-95e8-03f552ee70fc">

**Comment by p0deje** [comment] 2024-11-09 20:07
Likely because CleanClip is not a sandboxed application.

**Comment by PFarrell90** [comment] 2024-11-26 21:40
Cross-posting this for community benefit, this limitation put in place by Apple should be reverted whenever `15.2` is released (timeline... tbd?): https://developer.apple.com/forums/thread/763878?page=2

<img width="958" alt="image" src="https://github.com/user-attachments/assets/990fe06f-3467-42f9-a503-ca2b3222c320">

Also posted on the original/oldest issue: 
https://github.com/p0deje/Maccy/issues/813#issuecomment-2501981404

**Comment by p0deje** [comment] 2024-11-26 22:35
I can confirm that in recent macOS 15.2 Beta (24C5073e) it's again possible to use Option+V shortcut.

**Comment by shichanglin5** [comment] 2024-11-27 11:42
nice
