### ISSUE TITLE
"Paste Automatically" changes focus to the wrong display

### ISSUE THREAD

**Issue by sabrina-s** [p0deje/Maccy#460] opened 2022-09-12 08:55 UTC
**Steps to replicate:**
- enable 'paste automatically' feature in maccy preferences
- bring up maccy menu on external monitor (extended display)
- hit 'enter'

**Expected behaviour:**
- text is pasted in focused textarea on the external display

**Actual behaviour:**
- text is pasted in the other monitor (main display)

**Notes:**
- OS: Monterey 12.3, but also experienced this on Big Sur previously
- the behaviour is erratic, it goes away at times, but it's hard to predict. rebooting the machine does not seem to make a difference.

**Comment by p0deje** [comment] 2022-09-12 14:22
Can you tell me which application you see this behavior with? During pasting Maccy attempts to return focus to the original application but if you have multiple windows of the same app - it doesn't really know which one to choose so it delegates this choice to macOS. It's possible that sometimes it's not working correctly and I'd like to check if this is related to particular applications (e.g. Firefox which is not a native Cocoa app).

For a while, as a workaround, you can enable "Avoid taking application focus" in Maccy advanced preferences.

**Comment by sabrina-s** [comment] 2022-09-13 02:59
@p0deje I've noticed this happening with Chrome and VSCode so far.
Thanks! I'll give that a try and observe if it reoccurs.

**Comment by p0deje** [comment] 2022-09-14 13:54
I've tested using VS Code and Chrome on two displays and it worked fine. Can you please provide more concrete steps to reproduce the issue?

**Comment by sabrina-s** [comment] 2022-09-15 15:20
@p0deje

1. Open 2 Chrome windows
2. Place window #1 to an external monitor
3. Place window #2 on the main macbook screen
4. Bring up maccy menu on textarea in window #1 and hit enter to automatically paste (the text is pasted on a textarea in window #2 instead)

I've also just tested again to confirm that enabling "avoid taking application focus" helps prevent the above issue.

**Comment by p0deje** [comment] 2022-09-16 16:52
@sabrina-s I followed your steps but I still cannot reproduce the problem. Can you please share additionally the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by sabrina-s** [comment] 2022-09-19 00:57
Here you go:

```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "NSWindow Frame SUStatusFrame" = "2488 1821 400 134 1728 1117 1920 1055 ";
    "NSWindow Frame SUUpdateAlert" = "2378 1623 620 398 1728 1117 1920 1055 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "643 363 442 405 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2022-09-18 08:53:17 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 1557423230;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.tiff",
        "public.file-url",
        "public.png"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
    };
    pasteByDefault = 1;
    removeFormattingByDefault = 1;
}
```

**Comment by sabrina-s** [comment] 2022-09-19 13:45
I can only think of [Rectangle](https://rectangleapp.com/). Let me try to replicate the issue tomorrow and see if it goes away if I quit Rectangle.

**Comment by sabrina-s** [comment] 2022-09-20 05:55
Just quit Rectangle and tried it again with 2 VSCode windows on either screen - I was able to replicate the issue.
I don't believe I'm running something else that controls the windows.

**Comment by p0deje** [comment] 2022-09-20 14:26
Unfortunately, I still cannot reproduce it and I'm out of ideas on what else to try. Can you keep using "Avoid taking application focus" as a workaround?

**Comment by sabrina-s** [comment] 2022-09-21 02:27
Yup, that sounds good. Thanks!

**Comment by p0deje** [comment] 2022-09-21 03:35
I'm going to close this issue since there is nothing I can do about it at the moment. I'll reopen if somebody reports this too with additional details.

**Closed by p0deje** 2022-09-21 03:35 UTC
Labels: bug, needs triaging

**Comment by wookayin** [comment] 2023-01-03 09:18
This bug happens everywhere with basically ANY applications and at all times, but "Avoid taking application focus" seems a good workaround.
