### ISSUE TITLE
maccy crashes when searching

### ISSUE THREAD

**Issue by bucketfishy** [p0deje/Maccy#403] opened 2022-05-12 02:31 UTC
when i try to search for something, maccy occasionally crashes. i started using maccy around january this year and this bug happens on all versions that i've updated to so far. i tried to search to see whether someone reported this issue already, but i couldn't find any. apologies in advance if this is a duplicate!

unfortunately, it's been difficult finding the reason—it happens inconsistently. i've attached a screen recording and here's what happened in it, in case it's hard to see:
1. clipboard consists of "a", "b", "c", "efg" (from oldest to most recent) among other things
2. i search for 'a'. it works and i click on it
3. i search 'efg'. it crashes
4. i reopen maccy
5. i search 'b'. it works
6. i search 'e'. it crashes
(after reopening (off-video), i searched 'c' and it crashed.)

https://user-images.githubusercontent.com/66538443/167979735-c667fd86-fc2d-4cb7-a0e8-58d55016f2e6.mov

 i'm on the latest maccy build (0.22.2 (11)) and i'm on macos monterey version 12.0.1. sorry i couldn't provide more info or figure out the specific reason it crashes—let me know if i can help further in any way.

**Comment by Axenntio** [comment] 2022-05-12 16:52
I think you will need to provide the content of you clipboard history (you can get it here `$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite`) so we can try to reproduce the issue and debug it.

You can also give more information, did you enable FuzzySearch ?

If you absolutely need the app to works now, you can make a backup of the file `Storage.sqlite` to keep your datas safe (until issue fixed), and delete every entry `⌥+⌘+delete` in Maccy.

**Comment by p0deje** [comment] 2022-05-16 18:53
I'm pretty sure it's related to the data you store, maybe some particular content causes the crash when searching. The only way to reproduce and fix the bug is to debug using your copy of `$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite` as @Axenntio said. If you could clear it from confidential information and upload it to this issue, it would be useful.

**Comment by p0deje** [comment] 2022-05-31 21:42
@bucketfishy `Storage.sqlite` is updated when you exit Maccy. Unfortunately, I can't debug without this file. If you could quit Maccy and then upload all `Storage.*` files - it would be helpful.

**Comment by p0deje** [comment] 2022-07-31 21:46
Closing since no reply for more than a month.

**Closed by p0deje** 2022-07-31 21:46 UTC
Labels: bug, needs triaging
