### ISSUE TITLE
Unable to interact with Sparkle update prompt unless Preferences window is also open

### ISSUE THREAD

**Issue by daprice** [p0deje/Maccy#371] opened 2022-02-10 00:18 UTC
I just encountered this issue when updating from 0.22.0 (installed via Homebrew) to 0.22.1 on macOS 12.2. The automatic Sparkle update prompt is only visible when the Maccy menu is open, but attempting to click any of the buttons in the prompt (Install, Cancel, etc) causes both the menu and update prompt to disappear, making the update prompt un-interactable. To be able to update, I had to also open Maccy’s Preferences window, which allowed the Sparkle prompt to remain on the screen.

I have “Check for updates automatically” enabled, “Show menu icon” disabled, and “Avoid taking application focus” disabled, in case any of those options affect this.

Steps to reproduce:
1. Have Maccy running in the background with the above configuration options.
2. (an update is released, Maccy automatically checks and finds the update)
3. Press the Maccy hotkey to open the menu, which also makes the Sparkle update prompt visible.
4. Try to click the Update button in the Sparkle prompt.

Result: the click does not register, because it causes the update prompt to immediately disappear along with the clipboard history menu. This can only be avoided by having the Preferences window open at the same time.

**Comment by p0deje** [comment] 2022-02-12 05:12
I cannot reproduce this issue. The auto-update window only shows for me when I open preferences window. After that, the update window remains open even if close the popup and/or preferences window. I have an idea why the issue might happen, but need to debug more to fix it and I can't reproduce at the moment.

**Comment by p0deje** [comment] 2022-02-12 05:36
Found a way, should be fixed now and available in the next release.

**Closed** 2022-02-12 05:36 UTC
Labels: bug
