### ISSUE TITLE
Search without results breaks Maccy window

### ISSUE THREAD

**Issue by murermader** [p0deje/Maccy#671] opened 2023-11-07 16:40 UTC
Hi,

I just wanted to share some strange behaviour I am experiencing, that happens when I search for something that does not match anything. I am using the search mode **Exact**. 

There are multiple issues:
- When searching for any text (that does not match any items), then deleting the text, some items will be shown multiple times. Only the first entry will have a keyboard shortcut. This can happen with one or multiple items!
- After an item has been duplicated, the items without a keyboard shortcut cannot be reached with keyboard navigation.
- When showing items twice, the window size is wrong, which cuts off the menu options at the bottom.
- Scrolling inside this 'too small' window causes the Maccy window to move in strange ways.
- When items are pinned, they will also get duplicated, if they were found by the search, and added back in not only at the top.
- Closing and reopening the Maccy window fixes the issue (temporarily)

I think the following is the problem: 
When the search does not yield any results, Maccy shows the latest copied items (instead of nothing?). When deleting the search text, the items from the search view are not removed, but the items from the default view are added back in. There are more items in the default view than accounted for, which leads to the other weird behaviour described above.

I recorded a video to showcase the problem: https://share.cleanshot.com/cZbVKyCM (Ignore Pinned Item, I thought at first this only happens when items are pinned)

**Comment by p0deje** [comment] 2023-11-07 18:59
@murermader Are you running Maccy 0.28? This should be fixed there.

**Comment by murermader** [comment] 2023-11-07 19:01
Yes. From the about window: Version 0.28.0 (23)

**Comment by p0deje** [comment] 2023-11-07 19:07
Strange, I cannot reproduce. What macOS version do you run?

https://github.com/p0deje/Maccy/assets/665846/2761d8c3-ff54-419a-925c-4903860e7e3e

**Comment by murermader** [comment] 2023-11-07 19:09
Thank you for trying to reproduce it. Strange that it only happens for me. Maybe there is something more to it.

I am on macOS Sonoma (14.0 (23A344)).

**Comment by p0deje** [comment] 2023-11-07 19:12
Can you try upgrading to Sonoma 14.1?

**Comment by murermader** [comment] 2023-11-07 19:36
Upgrading to Sonoma 14.1 seems to have fixed the issue. I can no longer reproduce it.

**Comment by p0deje** [comment] 2023-11-07 19:37
Good to know, I guess we can close it then. Feel free to re-open if you see it again.

**Closed by p0deje** 2023-11-07 19:37 UTC

**Comment by murermader** [comment] 2023-11-07 19:39
Thank you for your support!
