### ISSUE TITLE
keeps on scrolling

### ISSUE THREAD

**Issue by FernandoMiguel** [p0deje/Maccy#197] opened 2020-11-12 13:35 UTC
* cmd+shift-c
* arrow up

expected:
* to stay in the bottom of the list

what happens instead
* the highlight keeps scrolling to the top in a loop

details:
v0.18 
large list (100?) bigger than the screen size

**Comment by p0deje** [comment] 2020-11-12 19:24
That's by design. Any reason why the scrolling should stop when reaching the top/bottom?

**Comment by FernandoMiguel** [comment] 2020-11-12 19:26
Maybe I'm not being clear.
It scrolls by it self... Non stop.
So I can't select what is at the bottom, like preferences

**Comment by p0deje** [comment] 2020-11-12 19:38
Wait, what? Can you record a video? I can't reproduce.

**Comment by FernandoMiguel** [comment] 2020-11-12 19:40
Yeah freaky 😊
I'll try tomorrow when I'm back at work..

At least one time it didn't behave like that.

Could it be it was still updating something after installing the new version?

**Comment by FernandoMiguel** [comment] 2020-11-12 19:40
I remember I couldn't click in the task bar icon and open the list at the time.

**Comment by p0deje** [comment] 2021-01-25 20:04
Closing since no news for a month. Please reopen with more details.

**Closed by p0deje** 2021-01-25 20:04 UTC
Labels: needs triaging
