### ISSUE TITLE
Pins Keep Disappearing After using them

### ISSUE THREAD

**Issue by MisterRK** [p0deje/Maccy#193] opened 2020-11-02 16:41 UTC
Hi there,
Love the application saves me so much time and headache. I've noticed with the most recent update that my pins disappear from the list after using them. If I reload the app or change the location of the pins setting they come back to normal. 

Hope the team can get this fixed! Love the app!

I don't know if my skill set as a developer could be used by your team but I am always looking for fun open source to contribute to!

**Comment by p0deje** [comment] 2020-11-04 21:09
Duplicate of #187

**Closed by p0deje** 2020-11-04 21:09 UTC
