### ISSUE TITLE
⌥⇧C to open Maccy does not work on MacOS Sequoia public beta

### ISSUE THREAD

**Issue by frankshrestha** [p0deje/Maccy#813] opened 2024-07-16 15:25 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

1.0.0

### macOS Version

Version 15.0 Beta (24A5289h)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2560,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUUpdateAlert" = "530 470 620 398 0 0 1680 1025 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "619 426 542 436 0 0 1680 1025 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-07-16 15:19:55 +0000";
    SUUpdateGroupIdentifier = 896378367;
    avoidTakingFocus = 0;
    clearSystemClipboard = 1;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.html",
        "public.utf8-plain-text"
    );
    hideFooter = 1;
    hideSearch = 0;
    hideTitle = 1;
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "net.antelle.keeweb"
    );
    imageMaxHeight = 40;
    maxMenuItemLength = 50;
    maxMenuItems = 20;
    menuIcon = maccy;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 0;
    pinTo = top;
    popupPosition = center;
    popupScreen = 0;
    previewDelay = 1500;
    removeFormattingByDefault = 0;
    showInStatusBar = 0;
    showRecentCopyInMenuBar = 0;
    showSpecialSymbols = 1;
    suppressClearAlert = 1;
}
```

### Description

Setting ⌥⇧C to open maccy does not work on MacOS Sequoia public beta.

### Steps to Reproduce

Set `⌥⇧C` as a shortcut to open Maccy. Press the assigned shortcut.

**Comment by p0deje** [comment] 2024-07-16 15:59
It's the same as https://github.com/sindresorhus/KeyboardShortcuts/issues/176, not sure how to fix it though. Can you please report this issue to Apple using Feedback Assistant?

**Comment by jasudev** [comment] 2024-07-17 02:19
I'm experiencing the same thing, the shortcut doesn't work in the macOS Sequoia beta version.

**Comment by frankshrestha** [comment] 2024-09-11 02:14
I tried binding the same shortcut on MacOS Version 15.0 (24A335). Still does not open but if you open Maccy and then press the shortcut, it will close.

**Comment by p0deje** [comment] 2024-09-11 02:22
> I tried binding the same shortcut on MacOS Version 15.0 (24A335). Still does not open but if you open Maccy and then press the shortcut, it will close.

Shortcuts when window is closed are set globally and when window is open - locally. That's why the former doesn't work while the latter works.

**Comment by p0deje** [comment] 2024-09-18 04:10
A workaround mentioned in #872 by @AbrarTheCrypto 

> macOS 15 has disabled all shortcuts using “Option + any letter.” To fix this, follow these steps to restore your Maccy shortcut:
> 1.	Go to System Settings > Keyboard > Keyboard Shortcuts > Modifier Keys.
> 2.	Change the “Option” key to “Command” or another key of your choice.
> 3.	Restart your Mac to apply the changes.
> After this, your old Maccy hotkey will work just like before.

**Comment by frankshrestha** [comment] 2024-09-18 06:12
That would affect all shortcuts in all programs, wouldn't it?

**Comment by Donjae-Wang** [comment] 2024-09-22 15:35
Same bug in Sequoia 15.0. When I use the [easydict](https://github.com/tisfeng/Easydict) I can use the opt-d shortcut key. I don’t know if the shortcut key implementation method is different.

**Comment by p0deje** [comment] 2024-09-23 02:38
Easydict application is not sandboxed, that’s why it’s not affected. On Sep 22, 2024, at 08:36, Donjae Wang ***@***.***> wrote:﻿
Same bug in Sequoia 15.0. When I use the easydict I can use the opt-d shortcut key. I don’t know if the shortcut key implementation method is different.

**Comment by IkonicR** [comment] 2024-09-23 13:28
Is there a fix for this yet?? Very annoying.. Also I don't want to change the system settings as that will change all my other shortcuts?

**Comment by p0deje** [comment] 2024-09-23 14:33
Cross-posting from https://github.com/sindresorhus/KeyboardShortcuts/issues/176#issuecomment-2361446272

> Looks like we have our answer: https://developer.apple.com/forums//thread/763878?src=push&answerId=804374022#804374022
> 
> Frameworks Engineer
> Apple
> 
> This was an intentional change in macOS Sequoia to limit the ability of key-logging malware to observe keys in other applications. The issue of concern was that shift+option can be used to generate alternate characters in passwords, such as Ø (shift-option-O).
> 
> There is no workaround; macOS Sequoia now requires that a hotkey registration use at least one modifier that is not shift or option.

**Comment by AlbertQM** [comment] 2024-09-24 14:13
> Cross-posting from [sindresorhus/KeyboardShortcuts#176 (comment)](https://github.com/sindresorhus/KeyboardShortcuts/issues/176#issuecomment-2361446272)
> 
> > Looks like we have our answer: https://developer.apple.com/forums//thread/763878?src=push&answerId=804374022#804374022
> > Frameworks Engineer
> > Apple
> > This was an intentional change in macOS Sequoia to limit the ability of key-logging malware to observe keys in other applications. The issue of concern was that shift+option can be used to generate alternate characters in passwords, such as Ø (shift-option-O).
> > There is no workaround; macOS Sequoia now requires that a hotkey registration use at least one modifier that is not shift or option.

That's unfortunate, thanks a lot for sharing!

I've switched to ⇧⌃C, works like a charm (except for the muscle memory 😄 )

**Comment by webdev69420** [comment] 2024-09-30 10:09
Workaround for people that don't want to have to change Maccy shortcuts in macOS 15.0 Sequoia:
[https://www.reddit.com/r/macapps/comments/1fjpiiw/comment/lolslnm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](https://www.reddit.com/r/macapps/comments/1fjpiiw/comment/lolslnm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by frankshrestha** [comment] 2024-09-30 16:38
For people using Karabiner Elements, json for complex modification:

```
{
    "manipulators": [
        {
            "description": "Maccy: ⌥⇧C to ⌃⌥⌘⇧C",
            "from": {
                "key_code": "c",
                "modifiers": { "mandatory": ["left_option", "left_shift"] }
            },
            "to": [
                {
                    "key_code": "c",
                    "modifiers": ["left_control", "left_option", "left_command", "left_shift"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

This translates `⌥⇧C` to `⌃⌥⌘⇧C`.

**Comment by selimanajjar9** [comment] 2024-10-30 03:13
I also encountered the same problem. The shortcut of option+c is invalid. It's so uncomfortable.🤯How do I fix it?

**Comment by krispetkov** [comment] 2024-11-02 08:53
Another working solution is using [BTT](https://folivora.ai/):
1. Assign some key combination in Maccy app:
<img width="504" alt="image" src="https://github.com/user-attachments/assets/21eeb088-6c08-4b57-bb1d-02369793a0c8">

2. Set the bellow configuration if BTT to override `Opt+V`. The configuration should be created under the `Keyboard Shortcuts` section.
<img width="825" alt="image" src="https://github.com/user-attachments/assets/114324f4-1891-4de7-8398-cb0c728a0a1f">

**Closed** 2024-11-22 18:44 UTC
Labels: bug

**Comment by p0deje** [comment] 2024-11-26 22:36
I can confirm that in the recent macOS 15.2 Beta (24C5073e) it's again possible to use the Option+V shortcut.

**Comment by workzer** [comment] 2024-12-01 01:13
so all we need is to wait for 15.2 to be final ? right now I was able to assign a touch of my Logitech G to open up Maccy, looking forward to get the shortcut back.

**Comment by p0deje** [comment] 2024-12-02 01:27
> so all we need is to wait for 15.2 to be final

looks like, unless Apple changes their mind

**Comment by psiho** [comment] 2024-12-03 16:28
It's really simple to resolve this. I used skhd because I already have it on the system (for yabai shortcuts). It's really usefull on its own. Then, I've put Maccy shortcut to something I'll never press like: shift + alt + ctrl + cmd - v.

Then you only need single line in skhd config file (~/.config/skhdrc):
`latl - v : skhd -k "shift + alt + ctrl + cmd - v"`
... and that basicaly remaps what I want option+v to simulate what I configured in Maccy. You don't even need to restart skhd service, it reloads config automatically.

I'm pretty sure you can also do it with karabiner, but skhd is simpler in my opinion.

**Comment by ggrrll** [comment] 2024-12-04 16:07
> > I can confirm that in the recent macOS 15.2 Beta (24C5073e) it's again possible to use the Option+V shortcut.
> 
> thanks -- actually, for me no shortcut works ... I am using e.g. `ctrl + alt + cmd + h`

to be fair, sometimes it works... but not e.g. when I am inside a text box, in a webform , or when I am typing in my IDE, ...
in order to activate it , I have to move out of the box , and hopefully it activates -- sometimes , I have to click on the menu bar icon
