### ISSUE TITLE
Can't use searchbar anymore 

### ISSUE THREAD

**Issue by vandrieu** [p0deje/Maccy#645] opened 2023-10-17 11:53 UTC
Maccy worked great for months.

But I just updated it to the last version a few minutes ago, and now I can't search for text anymore:

https://github.com/p0deje/Maccy/assets/46876905/aaccfa1f-ebde-43ef-91e5-db50d593203f

**Comment by p0deje** [comment] 2023-10-17 17:49
Duplicate of #617, please see the discussion there.

**Closed by p0deje** 2023-10-17 17:49 UTC

**Comment by vandrieu** [comment] 2023-10-23 14:51
Upgrading to Maccy v0.28.0 fixed the issue.
