### ISSUE TITLE
Don't ask for app store reviews

### ISSUE THREAD

**Issue by margieharrison** [p0deje/Maccy#553] opened 2023-06-04 06:55 UTC

**Comment by margieharrison** [comment] 2023-06-04 06:56
@p0deje What are you trying to do here? Annoy people that paid for the app?

**Comment by margieharrison** [comment] 2023-06-04 06:58
https://github.com/p0deje/Maccy/commit/02cc9d4af8222601addbaf2b2035cf2f33f1b531

**Comment by p0deje** [comment] 2023-06-04 15:08
App Store Review popup is being shown:
- no more than 1 time per month
- no more than 3 times per year
- as long as Maccy was used 50+ times (by "usage" I mean some history item was selected in Maccy)

What's the problem with any of these? I'm trying to promote Maccy in the App Store and even though I know many people use it, still negative reviews dominate certain regions so that's my way of fixing the issue.

I know users can completely disable reviews by unchecking "In-App Ratings & Reviews" in the App Store Settings, so I decided not to implement a custom setting to control the behavior.

These are my reasons for adding this functionality. If you have any proposals, please let me know and hopefully, you also explain why something should be done in your way.

**Comment by p0deje** [comment] 2023-06-04 15:20
Ok, I looked through the history of the issue and I can see that the problem is that the popup is shown to users who didn't install it from the App Store 🤦‍♂️ Obviously, that's a bug I introduced and I'll fix it right away. I was sure that the StoreKit handles that for me, but it's not. My bad!

**Comment by p0deje** [comment] 2023-06-04 15:41
This is now fixed in 53c19ece510067874fa421a014d2028a6d79a920 - please update to 0.26.4. If you have any other concerns, feel free to reopen the issue.

**Closed by p0deje** 2023-06-04 15:41 UTC
