### ISSUE TITLE
[V2] Items are visible underneath pins if only one item is pinned

### ISSUE THREAD

**Issue by weisJ** [p0deje/Maccy#832] opened 2024-08-03 17:16 UTC
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.x

### Description

If only one item is pinned other items are visible beneath it when scrolling. Doesn't happen with more than one item.
<img width="367" alt="image" src="https://github.com/user-attachments/assets/6e80bd4e-1419-4ca7-9ddb-79ec3fb5ea2b">

**Comment by p0deje** [comment] 2024-08-03 20:52
I cannot reproduce. What macOS version do you run?
<img width="517" alt="Screenshot 2024-08-03 at 13 52 14" src="https://github.com/user-attachments/assets/e9ab8ee4-dfcc-4532-bd8c-892aa110e545">

**Comment by weisJ** [comment] 2024-08-03 20:55
14.5 (23F79). Might only be relevant if the header is hidden.

**Comment by p0deje** [comment] 2024-08-04 04:27
Should be fixed in beta 9

**Closed by p0deje** 2024-08-04 04:27 UTC
Labels: bug
