### ISSUE TITLE
Selection highlight still exist when nothing is matched

### ISSUE THREAD

**Issue by alvin96** [p0deje/Maccy#490] opened 2022-11-17 07:09 UTC
This is my clipboard content when I highlight the text

<img width="300" alt="image" src="https://user-images.githubusercontent.com/20142859/202378187-c9dbf624-a562-4758-8fbe-622f0da56e2f.png">

And this is when I search text which didn't exist in maccy, it still shows the selection highlight
<img width="298" alt="image" src="https://user-images.githubusercontent.com/20142859/202378427-c31e830a-cedc-4765-bfbf-8daf4bea7325.png">

MacOS version: 
Ventura 13.0.1

P.S. The default highlight color is blue, mine is in red due to I change my system accent color

**Comment by p0deje** [comment] 2022-11-17 17:38
Duplicate of #475

**Closed** 2022-11-18 03:05 UTC
