### ISSUE TITLE
feature request: scrollbar, fixed footer

### ISSUE THREAD

**Issue by reslear** [p0deje/Maccy#483] opened 2022-11-04 21:34 UTC
hi) hx for good util) i suggest two feature:

1. add simple scrollbar
<img width="504" alt="Screenshot 2022-11-04 at 22 30 59" src="https://user-images.githubusercontent.com/12596485/200077949-baa362d1-b6b3-435f-8dbb-067d7ae71b4c.png">

2. and sticky fixed bottom footer on scroll 
<img width="494" alt="Screenshot 2022-11-04 at 22 31 58" src="https://user-images.githubusercontent.com/12596485/200078084-c0491569-7e48-4895-94eb-df993573e709.png">

**Comment by p0deje** [comment] 2022-11-06 19:39
Duplicate of #229

**Closed by p0deje** 2022-11-06 19:39 UTC
