### ISSUE TITLE
Fresh Maccy install won't start on MacOS Catalina

### ISSUE THREAD

**Issue by dannylevenson** [p0deje/Maccy#52] opened 2019-10-15 11:13 UTC
I just read about Maccy in the Dense Discovery news letter, so I thought I'd give it a try. Installing it via brew was not a problem, but when I try to start it, I get a pop-up that says:

> “Maccy.app” can’t be opened because Apple cannot check it for malicious software.
>
> This software needs to be updated. Contact the developer for more information.
>
> Homebrew Cask downloaded this file today at 6:59 AM from github.com.

**Comment by p0deje** [comment] 2019-10-15 15:03
The internet suggests the workaround is to:

1. Move the app to /Applications.
2. Right-click in Finder and select "Open".

Can you try that?

**Comment by richardvenneman** [comment] 2019-10-16 11:41
I can confirm this issue occurs after trying to open the app (which I downloaded from https://maccy.app and moved to /Applications).

<img width="532" alt="Screenshot 2019-10-16 at 13 40 50" src="https://user-images.githubusercontent.com/75705/66915984-928c6080-f01a-11e9-9be0-5e6d59e91c5f.png">

**Comment by DaFuqtor** [comment] 2019-10-25 21:08
Well, "Right-click in Finder and select `Open`" means exactly that. Double clicking or pressing `Cmd` + `↓` won't work.

**Comment by ItsRyanWu** [comment] 2019-11-14 02:24
> The internet suggests the workaround is to:
> 
> 1. Move the app to /Applications.
> 2. Right-click in Finder and select "Open".
> 
> Can you try that?

This works

**Comment by limbic** [comment] 2019-12-02 19:19
This is still happening for me. I have tried moving to applications and right clicking to open.

**Comment by grrowl** [comment] 2020-01-07 12:44
I got the same message, here's how I fixed it (10.15.2)

* "“Maccy.app” can’t be opened because Apple cannot check it for malicious software." > Click "Show in Finder"
* Right click > Open
* Same message, but there's an additional button "Open" next to Cancel
* Clicking that opened the app — I had to check the app bar for it, but it's there and works.

**Comment by jadchaar** [comment] 2020-02-08 16:49
I fixed this by going to system preferences => security and privacy => in the general tab, click "open anyways" at the bottom.

@p0deje this is occuring because the app is not notarized. This will become a problem when Apple enforces notarization more strictly soon: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution.

**Comment by orens** [comment] 2020-05-12 08:44
Just had this problem. The resolution offered by @ItsRyanWu solved it for me.
Until it is solved, I suggest adding a comment about it in the “Installation” section in the docs

**Comment by jadchaar** [comment] 2020-06-06 16:34
@p0deje have you ever considered distributing Maccy via the Mac App Store (while still keeping it open source, of course)? Could be a nice medium for gaining users.

**Comment by p0deje** [comment] 2020-06-06 16:41
That's my current plan: https://twitter.com/p0deje/status/1268522596926140416

**Comment by jadchaar** [comment] 2020-06-07 17:13
> That's my current plan: https://twitter.com/p0deje/status/1268522596926140416

Adding a Tidelift link and sponsorship button on Twitter could be a good way to solicit donations to fund the Apple Dev subscription.

**Comment by FernandoMiguel** [comment] 2020-06-07 18:11
If you have github donations, I'll contribute right now.
I use and depend on this tool daily

**Comment by jadchaar** [comment] 2020-06-07 18:18
> If you have github donations, I'll contribute right now.
> I use and depend on this tool daily

Same here!

**Closed** 2020-06-08 12:47 UTC
Labels: bug

**Comment by saikiran91** [comment] 2020-06-11 05:33
> If you have github donations, I'll contribute right now.
> I use and depend on this tool daily

I will contribute as well.
