### ISSUE TITLE
Universal clipboard result show filepath on maccy

### ISSUE THREAD

**Issue by jjmmfi** [p0deje/Maccy#397] opened 2022-05-06 09:11 UTC
Copying from iPhone to Mac works well when using Apple universal clipboard, but the universal clipboard results show as in screenshots below. You can still copy them from Maccy and use them normally but this way to display them seems weird.
<img width="406" alt="image" src="https://user-images.githubusercontent.com/81366427/167102265-a5b1cbe5-125e-48ca-92c8-039211754dc3.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/81366427/167102498-fc40b6cf-b950-4dab-8bb7-c5b7b864d23e.png">

Using the latest version of IOS and macOS on iPhone X and Macbook Air M1.

**Comment by p0deje** [comment] 2022-05-31 21:44
@jeremiasmanninen Do you copy files or something else? Can you provide steps to reproduce this?

**Comment by fabifabulousity** [comment] 2022-06-09 11:42
I noticed this behaviour as well. Happens, e.g., when I copy text from my iPhone.

**Comment by p0deje** [comment] 2022-06-09 13:03
I can reproduce the problem, I'll need to investigate this.

**Comment by p0deje** [comment] 2022-08-10 20:51
I no longer can reproduce the issue using macOS 12.5. It could have been an issue of Universal Clipboard that is now fixed. Please reopen if you still see it.

**Comment by jeffzyliu** [comment] 2022-10-24 04:33
this is now happening to me, macOS 12.6, iPadOS 15.7

**Comment by p0deje** [comment] 2022-11-13 22:08
Not reproducing anymore 🤷‍♂️
Seems like an intermittent problem with how Apple handles Universal Clipboard

**Comment by SuibianP** [comment] 2023-06-06 07:54
Same issue on macOS 13.4 and iOS 16.5. Reproducible when I copy text from a Safari webpage on iPhone.

On a side note it also shows a prompt ("Copying 1 item from 'iPhone'...") for several seconds.

<img width="467" alt="image" src="https://github.com/p0deje/Maccy/assets/59951032/5a8d10ea-c28e-4665-8685-a9450374bf3c">


Possibly related: https://github.com/gnachman/iTerm2/commit/e20198a704b1d7705d5b866ad3c87df72d271997

**Comment by p0deje** [comment] 2023-06-06 13:26
If I understand correctly, iTerm would read the URL and copy the contents? I don't think it would be possible in Maccy since all network communication is restricted by the app sandbox.

**Comment by SuibianP** [comment] 2023-06-07 04:35
As per <https://stackoverflow.com/questions/71366532/read-files-from-pasteboard-file-url-inside-macos-sandbox>, the URI seems to be automatically granted access to the sandboxed application.

I would assume it to be possible as clipboard contents are meant to be public even to sandboxed applications.

At the very least, it can be less confusing if some placeholder text like "*Copied content via Handoff*" is displayed instead of a random-looking URI.

**Closed** 2023-07-13 15:11 UTC
Labels: bug
