### ISSUE TITLE
Potential Memory Issues & Color Wheel of Death 

### ISSUE THREAD

**Issue by PatrickUtz** [p0deje/Maccy#726] opened 2024-02-05 01:26 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Description

I'm starting to get the color wheel of death every 10 - 30 min, and have a feeling it might be tied to Maccy. Wondering why it's taking up so much memory? I only have the history set to 20 items. 

<img width="1005" alt="image" src="https://github.com/p0deje/Maccy/assets/30327204/8da52bb7-6a5e-44fa-b72d-49a836eb315d">

**Comment by p0deje** [comment] 2024-02-05 14:42
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by jhult** [comment] 2024-02-13 17:51
On a side note, do we know roughly how much memory usage to expect? Perhaps that is heavily dependent on the search mode and history limit.

**Comment by jhult** [comment] 2024-02-13 17:57
Related discussion: https://github.com/p0deje/Maccy/issues/384

**Comment by p0deje** [comment] 2024-03-10 22:06
Closing as duplicate of #384

**Closed by p0deje** 2024-03-10 22:06 UTC
Labels: bug
