### ISSUE TITLE
Feature request: items folders for quick access but keeping space taken on screen small 

### ISSUE THREAD

**Issue by nicolnt** [p0deje/Maccy#581] opened 2023-07-18 12:30 UTC
This feature request is directly inspired from https://github.com/Clipy/Clipy
Issue is well described here: 
https://github.com/Clipy/Clipy/issues/508#issuecomment-1234234893

Search is not always convenient, so a list of items and search bar complement each other well. But to prevent long lists, we can use a folder system.

It looks like screenshot below:
<img width="400" alt="image" src="https://github.com/p0deje/Maccy/assets/12377588/84a586cb-926c-4f77-905f-f33045e10788">

Clippy configuration lets the user choose the number of items shown, which is pretty ideal:
<img width="475" alt="image" src="https://github.com/p0deje/Maccy/assets/12377588/1b56adb1-30e2-48b4-980f-6631f732e8a9">

**Comment by p0deje** [comment] 2023-07-18 14:48
Duplicate of #229

**Closed by p0deje** 2023-07-18 14:48 UTC
