### ISSUE TITLE
Stopped working on 10.15.5

### ISSUE THREAD

**Issue by PkAIR** [p0deje/Maccy#121] opened 2020-06-12 13:16 UTC
Version 0.11 stopped working on 10.15.5 after restart of the computer. 

After hitting combination to bring maccy popup it was killed (icon disappeared from the top bar)

How can I provide more info to you?

**Comment by FernandoMiguel** [comment] 2020-06-13 15:27
same here. was fine yesterday

**Comment by FernandoMiguel** [comment] 2020-06-13 15:28
maybe related to https://github.com/p0deje/Maccy/issues/115  ?

**Comment by p0deje** [comment] 2020-06-13 17:23
Please try on 0.12 - it's likely fixed. I'll close the issue, but feel free to re-open if it's still present.

**Comment by p0deje** [comment] 2020-06-13 17:23
Duplicate of #115

**Comment by FernandoMiguel** [comment] 2020-06-13 17:27
@p0deje there's no 0.12

**Comment by p0deje** [comment] 2020-06-13 17:32
Oh, right, I misread the problem. Could you try https://github.com/p0deje/Maccy/issues/115#issuecomment-642437517?

**Comment by FernandoMiguel** [comment] 2020-06-13 17:46
@p0deje for me deleting those folders fixed the issue.
it's weird cause i've been flipping between 0.10, 0.11, and even the test version of 0.12 and all was fine.
today it crashed.

@PkAIR does it fix for you?

**Comment by PkAIR** [comment] 2020-06-13 18:09
@FernandoMiguel going to try now!

**Comment by PkAIR** [comment] 2020-06-13 18:46
@FernandoMiguel indeed, now it works for me also after I deleted prev version completely with appcleaner. 

thank you so much. 

@p0deje thank you for such a cool and lightweight app!

**Comment by FernandoMiguel** [comment] 2020-06-13 18:49
Feel free to close the ticket

**Closed** 2020-06-13 19:05 UTC
Labels: bug

**Comment by p0deje** [comment] 2020-06-13 19:29
I've found another issue that could potentially cause a similar crash. The fix is 8a59482 and will be released in 0.12. I'm almost sure that is the cause of the crash reported here.

**Comment by PkAIR** [comment] 2020-06-13 20:14
@p0deje good news! waiting for the new build.

**Comment by p0deje** [comment] 2020-06-17 11:46
Please upgrade to 0.12. In order to upgrade, either install from Github if you can't start Maccy or cleanup the history by removing `~/Library/Application Support/Maccy/Storage.sqlite` file - that should allow Maccy to start so you could upgrade.

**Comment by PkAIR** [comment] 2020-06-17 17:11
@p0deje update was really smooth and straightforward. works like a charm
