### ISSUE TITLE
Select all/something in search bar via keyboard "shortcut"

### ISSUE THREAD

**Issue by kevin-heil** [p0deje/Maccy#246] opened 2021-02-25 10:31 UTC
Hi there,
first of all: thanks a lot for this tool!

In the daily use I encountered a minor inconvenience:
It's not possible to select single words or character via Keyboard Shortcut in the search field.

<kbd>SHIFT (⇧)</kbd> - for single character selection
<kbd>SHIFT (⇧)</kbd> + <kbd>ALT (⌥)</kbd> + <kbd>Arrow (← / →)</kbd> - for word selection
<kbd>CMD (⌘)</kbd> + <kbd>A</kbd> - for selecting whole phrase

It would be a blast if you could add this in one of the next releases.

**Comment by p0deje** [comment] 2021-02-28 04:50
This is kind of by design because the search field is kept unfocused in favor of the menu items. One can still manually focus the field and then most of the shortcuts will work.

I normally use the following shortcuts which are supported by Maccy:

* <kbd>COMMAND + DELETE</kbd> clears the search field
* <kbd>CONTROL + W</kbd> removes the last word from the search

I can add more shortcuts to manipulate if you can provide some examples.

**Comment by kevin-heil** [comment] 2021-03-01 17:29
Ah, I see. Never mind then. 
With mentioning <kbd>COMMAND + DELETE</kbd> and <kbd>CONTROL + W</kbd> you helped me a lot.

**Comment by p0deje** [comment] 2021-03-02 17:30
Alright, closing then.

**Closed by p0deje** 2021-03-02 17:30 UTC
Labels: enhancement, needs triaging
