### ISSUE TITLE
VSCode Pasting Issues with Multiple Displays

### ISSUE THREAD

**Issue by ndianabasi** [p0deje/Maccy#598] opened 2023-08-10 12:47 UTC
I've been struggled with this for a very long time, so I'm finally raising this as a bug.

I'm currently on `v0.24.0`.

If I have multiple VSCode windows opened across two displays, when I paste from the app, it pastes into the other window opened in the other display/monitor instead of the one which was focused earlier before the shortcut was executed.

I have a paid license for the product.

**Comment by p0deje** [comment] 2023-08-10 12:59
There is not much I can do about it, it's being working and not working for Electron-based apps and Chrome. Sometimes when you activate the Chrome window - it activates not the most recent one, but a different one - that's exactly what happens during paste. Closing this as it's duplicate of #534

**Closed by p0deje** 2023-08-10 12:59 UTC
