### ISSUE TITLE
on Maccy pop-up-window Cmd+V not paste my shortcut pinned item, and instead it paste current item to search text inputbox.

### ISSUE THREAD

**Issue by jixiangqd** [p0deje/Maccy#860] opened 2024-09-04 07:34 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0.beta.13 (44)

### macOS Version

14.6.1 (23G93)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 5849;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "598 511 710 443 0 0 1728 1079 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SUSendProfileInfo = 0;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.png",
        "public.file-url",
        "public.tiff",
        "public.rtf",
        "public.html"
    );
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "Pasteboard generator type"
    );
    maxMenuItemLength = 50;
    menuIcon = clipboard;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    popupPosition = center;
    popupScreen = 0;
    removeFormattingByDefault = 0;
    searchMode = mixed;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showSpecialSymbols = 1;
    showTitle = 1;
    windowSize = "[450,800]";
}
```

### Description

on Maccy pop-up-window Cmd+V not paste my shortcut pinned item, and instead it paste current item to search text inputbox.

### Steps to Reproduce

1.pin an item and set shortcut to v
2.use shortcut popup Maccy. and press cmd+v

**Comment by p0deje** [comment] 2024-09-04 20:06
Indeed, now in 2.0 the search field is always focused so pressing CMD+V would trigger a paste into it. I lean towards keeping it as-is and instead restrict using "V" as a pinned item letter. Any objections?

**Comment by jixiangqd** [comment] 2024-09-05 03:26
> Indeed, now in 2.0 the search field is always focused so pressing CMD+V would trigger a paste into it. I lean towards keeping it as-is and instead restrict using "V" as a pinned item letter. Any objections?

that's ok, I'm now change my shortcut away from cmd+v, that works fine.

**Comment by p0deje** [comment] 2024-09-06 19:41
Fixed in beta 14

**Closed by p0deje** 2024-09-06 19:41 UTC
Labels: bug

**Comment by P0stf1x** [comment] 2024-11-30 16:18
@p0deje I think there's a bug here. If I understand correctly the problem is only with command+v (⌘+V), but option+v (⌥+V) is also restricted

**Comment by p0deje** [comment] 2024-11-30 22:16
@P0stf1x wait till 15.2, it's fixed there
