### ISSUE TITLE
Feature request? Rearranging pinned items

### ISSUE THREAD

**Issue by Wild5au** [p0deje/Maccy#626] opened 2023-10-06 15:49 UTC
Hello - loving Maccy so far! What a game-changer. I would love to be able to rearrange my pins in a specific order - I use some many times each hour and would like those at the top as I'm not a short-cut user. I am wondering if the possibility to do this already exists and I am just missing it somewhere or if this would be possible to add?

**Comment by p0deje** [comment] 2023-10-06 15:59
Please see duplicate of #342

**Closed by p0deje** 2023-10-06 15:59 UTC
