### ISSUE TITLE
Features for disabling. 

### ISSUE THREAD

**Issue by seivan** [p0deje/Maccy#354] opened 2022-01-12 10:58 UTC
I don't mind adding these in a PR myself if you're ok with them, but I have a few suggestions. 

- [ ] Allow temporarily disable for the next item added on the Pasteboard (regardless of source) make sure menubar icon indicates this. 
- [x] Allow toggling disabled state by cmd click on the menu bar icon and make sure menubar icon indicates this. 

I could go either way with key-binds, however disabling for the the next item in the pasteboard, can't be a special "copy" key-bind, you might need this for things that come externally, like say `Screenshot to pasteboard` or stuff copied from iOS via handover. 

I noticed there is a [PR here](https://github.com/p0deje/Maccy/pull/242) and you got `option+rightclick` for disabling. 
There are a few issues.

- Time based stuff rarely works out, and people keep toggling to give themselves more time.
- `option+rightclick` is the wrong method for disabling, as it should be used to show additional information, maybe change to ~~`cmd+click`~~ `shift+click` - [Related](https://github.com/p0deje/Maccy/issues/355)

I can fix these as well. 

Edit: If it makes any difference I am not using a mouse, but the touch pad. And for me, it's not `option+click` but `option+rightclick` or technically, two finger press.

**Comment by p0deje** [comment] 2022-01-13 06:17
> Allow toggling disabled state by cmd click on the menu bar icon and make sure menubar icon indicates this.

Nothing to be done here per discussion in #355.

> Allow temporarily disable for the next item added on the Pasteboard (regardless of source) make sure menubar icon indicates this.

Can you elaborate more on the use-cases for such a feature?

**Comment by seivan** [comment] 2022-01-13 10:43
> > Allow toggling disabled state by cmd click on the menu bar icon and make sure menubar icon indicates this.
> 
> Nothing to be done here per discussion in #355.

My suggestion is to use `shift+click` for this instead of `option+rightclick`. As `option` is usually to show more context in the menu.
You can try it yourself on the Wifi or Bluetooth menu.
This is a perfect opportunity to show the settings and quit items even if they are disabled by the user. This is merely a UX improvement, and not really a big deal. 

 

> > Allow temporarily disable for the next item added on the Pasteboard (regardless of source) make sure menubar icon indicates this.
> 
> Can you elaborate more on the use-cases for such a feature?

I am about to take a screenshot that's copied to the clipboard. 
I use `shift+cmd+4` (not default) for this. 
But before doing that, I do the "disable next item" shortcut, either via UI or keybind - open for suggestions on which to use. 
Once the copy has been done, Maccy ignores it (doesn't store it) and re-enables itself. 
This helps for one-off copies that should not be stored, as opposed to a full disable.

**Comment by Stickyhavr** [comment] 2022-01-23 08:14
> My suggestion is to use `shift+click` for this instead of `option+rightclick`. As `option` is usually to show more context in the menu. 

Option+click is used to do an alternate function in the menu bar. For icons that have hidden information, like bluetooth or wifi, then it makes sense to display additional info. For items that can be disabled, like Maccy, or the Notification Center, I  would say option+click is the expected modifier.

**Comment by machale** [comment] 2022-02-04 23:35
I'm a little confused. I'm just starting to play with Maccy for the first time. From the above and #355 it sounds like I should be able to Option-Click, or maybe Option-Right-Click, on the menu bar icon to toggle Maccy being enabled or disabled. But I can't get any keystroke-click combination to do so. Am I supposed to be able to Option-(Right)Click to enable/disable?

I do see the _Advanced > Turn off_ option in the Preferences. I'd like to do exactly what it does without having to dig into the Preferences or go to the command line.

Maccy 0.22.0,9 installed via brew, macOS Monterey 12.1 (21C52).

If I'm misunderstanding what Option-(Right)Click is supposed to do, please let me know. In that case I'll likely open an enhancement request for a quick toggle feature. Thanks!

**Comment by Stickyhavr** [comment] 2022-02-05 02:13
I think there may be a bug in the latest version. I’m running three
versions behind (0.20.1) and option+click works perfectly.

I plan to update to the next version though once it comes out.

**Comment by p0deje** [comment] 2022-02-05 05:02
You are right, I totally forgot that there was a flaky bug when Option+Click stops working and I fixed it 7cf2933304d7871f4b9e51f2f704575d25f1a5dc. I couldn't reproduce it because I was running the master HEAD version locally.

I'll prepare a new release soon.

**Comment by p0deje** [comment] 2022-02-05 05:46
> I am about to take a screenshot that's copied to the clipboard.
I use shift+cmd+4 (not default) for this.
But before doing that, I do the "disable next item" shortcut, either via UI or keybind - open for suggestions on which to use.
Once the copy has been done, Maccy ignores it (doesn't store it) and re-enables itself.
This helps for one-off copies that should not be stored, as opposed to a full disable.

@seivan Ok, I see your use case. However, I still don't know how to make a nice UX for this feature. Would clicking on the menu icon with both Shift+Option pressed be enough?

The logic here is:

* Option+click toggles Maccy forever
* Option+Shifht+click toggles Maccy for the next copy only

**Comment by p0deje** [comment] 2022-02-05 11:43
The bug with option+click should be fixed in 0.22.1

**Comment by Stickyhavr** [comment] 2022-02-05 22:51
Hello,
I have upgraded to the latest version. However, I'm having the same problem I had the last time I tried to update. All my pins have gone invisible. I am able to run the terminal command described here: 
https://gist.github.com/p0deje/72cc0b408f5d7b47f59ee82772499711

Unfortunately, that only seems to last until my next reboot and then they are all invisible again.

Perhaps I will just paste all of my pins into a word document, and delete everything and start fresh. Just wondering if you had any advice for something else to try before I do that?  Thanks!

**Comment by machale** [comment] 2022-02-06 00:19
Confirmed Option-Click now works fine in 0.22.1 on macOS Monterey 12.1 (21C52).

Thanks for the super-quick update!

**_Minor_** issue, but I thought you should know: If you have _Preferences > Advanced_ open and Option-Click on the menu bar icon, the enable/disable works but the _Turn off_ checkbox in the Preferences pane does not immediately update. If you move to a different Preferences pane and then back to Advanced, the update shows just fine.

**Comment by p0deje** [comment] 2022-02-06 03:12
@Stickyhavr 

1. Only pins? What about unpinned? It might be a different bug if it only affects pins. Can you also try looking at the "Pins" tab in preferences and check if titles are shown there? You can also try to edit any title there and then restart app to check that it persists.
2. Does it only happen after reboot? What about quitting and restarting Maccy.app?
2. I mentioned this before, but this bug could happen if some older version of Maccy starts at login. Please try running `find . -name "Maccy*"` in Terminal.app - maybe you see some lingering version that somehow starts at login and messes up the database.

**Comment by Stickyhavr** [comment] 2022-02-06 14:46
You are correct on 1 and 2. I hadn’t noticed because I did a clear right
before I updated, so I didn’t have any other copies to lose.

And yes it was happening after closing and re-opening Maccy. I never close
Maccy, so I was associating that with a reboot but it was true any time the
app closed.

I used App Cleaner to get rid of all traces of Maccy, then installed the
latest version fresh. I’ll redo my pins manually.  I imagine I will be all
set now but I’ll let you know if I have any issues. Thanks!

**Comment by p0deje** [comment] 2022-02-10 03:36
@seivan Could you please take a look at https://github.com/p0deje/Maccy/issues/354#issuecomment-1030533095

**Comment by p0deje** [comment] 2022-05-31 22:24
So, folks, do we still need to do anything here? If there is still a need to have Maccy ignore the next copy, would Option+Shift+click work?

**Comment by Stickyhavr** [comment] 2022-05-31 22:31
Option + Click has been working fine for me.

Option + Shift + Click seems like a good choice to me for ignore next
copy.  Thanks for all that you do!

**Closed** 2022-06-03 15:49 UTC
Labels: enhancement, needs triaging
