### ISSUE TITLE
Shortcuts have low priority in Mac OS 15

### ISSUE THREAD

**Issue by Hsoron** [p0deje/Maccy#899] opened 2024-09-26 08:48 UTC
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.1

### macOS Version

15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":4096}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2304,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 391;
    "NSStatusItem Visible Item-1" = 0;
    NSUserKeyEquivalents =     {
        "\\U6253\\U5f00" = "~v";
    };
    "NSWindow Frame SUUpdateAlert" = "446 428 620 398 0 0 1512 944 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "501 385 510 473 0 0 1512 944 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-26 08:29:00 +0000";
    enabledPasteboardTypes =     (
        "public.html",
        "public.utf8-plain-text",
        "public.png",
        "public.tiff",
        "public.rtf"
    );
    historySize = 200;
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "Pasteboard generator type"
    );
    imageMaxHeight = 40;
    maxMenuItemLength = 50;
    maxMenuItems = 0;
    menuIcon = maccy;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showTitle = 0;
    windowSize = "[450,800]";
}
```

### Description

When I use the Option + V shortcut to open a window, the priority is lower than the system default checkmark, which prevents the window from opening

**Comment by p0deje** [comment] 2024-09-26 19:12
Duplicate of #813

**Closed by p0deje** 2024-09-26 19:12 UTC
Labels: bug
