### ISSUE TITLE
Maccy being very slow and freezing when saerching

### ISSUE THREAD

**Issue by sasa-b** [p0deje/Maccy#650] opened 2023-10-20 06:57 UTC
Since the Sonoma update Maccy started freezing when you try to search the clipboard history, it became really really slow to the point of not being usable, and sometimes it would even fully freeze.

**Comment by LetrixZ** [comment] 2023-10-20 15:36
Also, it's slower when pasting something

**Comment by p0deje** [comment] 2023-10-20 23:12
Duplicate of #617

**Closed by p0deje** 2023-10-20 23:12 UTC
