### ISSUE TITLE
Option + V shortcut is not working on MacOS 15

### ISSUE THREAD

**Issue by taaajii** [p0deje/Maccy#887] opened 2024-09-19 15:07 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0 (46)

### macOS Version

15

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":4096}";
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "501 388 510 479 0 0 1512 944 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-19 15:05:14 +0000";
    SUUpdateGroupIdentifier = 2045516388;
    avoidTakingFocus = 1;
    clearSystemClipboard = 1;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.file-url",
        "public.rtf",
        "public.html",
        "public.utf8-plain-text",
        "public.png"
    );
    historySize = 200;
    imageMaxHeight = 80;
    maxMenuItemLength = 80;
    maxMenuItems = 10;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    popupPosition = center;
    previewDelay = 1500;
    searchMode = mixed;
    showFooter = 1;
    showInStatusBar = 0;
    showSearch = 0;
    showSpecialSymbols = 0;
    showTitle = 0;
    suppressClearAlert = 1;
    windowSize = "[450,800]";
}
```

### Description

Below shortcut to open maccy is not working on MacOS 15 after upgrading my macos from 14 to 15
"Option + V"

It was working on MacOS14

**Comment by weisJ** [comment] 2024-09-20 12:16
Duplicate of #872

It's an issue with Apple. They disallowed Option + <key> shortcuts to be registered by applications.

**Closed** 2024-09-20 14:18 UTC
Labels: bug
