### ISSUE TITLE
Maccy not copying the text when using the command + C shortcut

### ISSUE THREAD

**Issue by lucifermickelson** [p0deje/Maccy#672] opened 2023-11-10 01:42 UTC
It doesn't copy the text when selecting the text and using command + C shortcut but it work when selecting copy from right click context menu
#bug

**Comment by p0deje** [comment] 2023-11-10 23:48
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by lucifermickelson** [comment] 2023-11-12 00:39
1. Version 0.28.0 (23) 
![Maccy Version](https://github.com/p0deje/Maccy/assets/81559076/36de3a1e-ef9e-4fa6-b334-db9560e36a67)
2.  Only show copy of few words long, not individual word, also not picking copy command command + c- not showing, all captured in the video below

https://github.com/p0deje/Maccy/assets/81559076/55c4f426-759f-4c28-8860-fa6d51c405ea

3. 
[maccy terminal output.docx](https://github.com/p0deje/Maccy/files/13326850/maccy.terminal.output.docx)

**Comment by p0deje** [comment] 2023-11-12 21:01
Looking at your video, Maccy also doesn't store a copy every time you select "Copy". There is nothing suspicious in your preferences, so I wonder what could it possibly be.

1. Does it only happen in Arc or in all other applications?
2. Do you run any other app that changes clipboard such as "Pure Paste"?

**Comment by ZizoPlayz** [comment] 2023-11-14 04:01
This also happened to me but I had "Pure Paste" enabled. When I quit "Pure Paste", "Maccy" works normally.

**Comment by ZizoPlayz** [comment] 2023-11-14 22:10
I turned off the setting compatibility setting and Maccy works with Pure Paste. I also removed all the Ignore settings. Thank you

**Comment by p0deje** [comment] 2023-11-16 02:49
@lucifermickelson It's possible that Arc marks copies as confidential and Maccy respects that. The same behavior can be observed in the private mode of Firefox. If that's the case, there is nothing Maccy can do about it. Please, double-check that by installing https://apps.apple.com/us/app/pasteboard-viewer/id1499215709?mt=12, then copying anything and posting here screenshot of the Pasteboard Viewer app. If you see something like `org.nspasteboard.ConcealedType` there - that's the case.

**Comment by dvirginz** [comment] 2023-11-18 09:46
Since upgrading to Sonoma, I have encountered this problem as well, and I am not using pure paste at all. Every time I copy, I find myself performing multiple cmd+c commands in order for the action to take effect.

**Comment by p0deje** [comment] 2023-11-21 23:47
@dvirginz Can you be more specific what's going wrong? Ideally:
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by dvirginz** [comment] 2023-11-22 07:27
Maccy version - 0.28.0

Here is a screen video. 
I understand it might be a bit hard to understand what's going on, so let me try to explain. 

My Maccy shortcut is Option+C. In the video, you can see how I'm marking words in a text, without clicking Command+C to copy them, and still, some of them, randomly, are being added to Maccy somehow. 

Moreover, after a few attempts, Maccy crashes. You can see how the last time I click Option+C, I get the sign √, which is my default Option+C sign when Maccy is not running.


https://github.com/p0deje/Maccy/assets/31047807/c1920fdd-f3e0-442a-8170-e8e7ce53cf9e

**Comment by p0deje** [comment] 2023-11-24 02:33
@dvirginz Ok, thanks for the update! 

I'm going to close this for now since it looks like the issue is solved.

**Closed by p0deje** 2023-11-24 02:33 UTC

**Comment by dbezic** [comment] 2024-09-19 23:30
@p0deje I have the same problem

1. Version:
<img width="280" alt="Screenshot 2024-09-20 at 00 27 32" src="https://github.com/user-attachments/assets/3a0d6482-e4f4-4c98-9881-6288a51da96b">

2. Recording:
https://github.com/user-attachments/assets/39077218-460a-44ae-9804-52b8d8cdb4c5

3. Output of `defaults read org.p0deje.Maccy`:
```
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "485 315 542 435 0 0 1512 944 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "501 458 710 385 0 0 1512 944 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    clearOnQuit = 1;
    enabledPasteboardTypes =     (
        "public.html",
        "public.png",
        "public.file-url",
        "public.tiff",
        "public.utf8-plain-text",
        "public.rtf"
    );
    ignoreEvents = 0;
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "net.antelle.keeweb"
    );
    imageMaxHeight = 50;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
        "2024-07-01-version-2" = 1;
    };
    numberOfUsages = 14;
    popupPosition = cursor;
    searchMode = fuzzy;
    showFooter = 1;
    showRecentCopyInMenuBar = 1;
    showSearch = 1;
    showTitle = 1;
    suppressClearAlert = 0;
    windowPosition = "[0.8220899470899471,0.868421052631579]";
    windowSize = "[450,169]";
}
```

**Comment by p0deje** [comment] 2024-09-20 04:22
@dbezic your Maccy window is too small to show all items, resize it to be beigger

**Comment by dbezic** [comment] 2024-09-20 14:14
<img width="709" alt="Screenshot 2024-09-20 at 15 13 43" src="https://github.com/user-attachments/assets/05af4a7d-a14c-4da6-b5e2-893cf43dcdf3">

Changed the size and nothing happens (even when quitting and reopening):
<img width="1038" alt="Screenshot 2024-09-20 at 15 14 24" src="https://github.com/user-attachments/assets/65198853-0c31-4f0e-a0b2-db1f9f29825a">

**Comment by p0deje** [comment] 2024-09-20 14:22
I think it's duplicate of #883

**Comment by dbezic** [comment] 2024-09-20 14:28
What is the fix for it, because I have "Text" selected: 
<img width="505" alt="Screenshot 2024-09-20 at 15 24 04" src="https://github.com/user-attachments/assets/47ae2301-4aa5-45c6-9ed7-3cffa2108dc6">

The issue in my case seems different since it is cutting the "Quit" text even.

I don't see any copied text cut off. Although the option "Show recent copy in the menu item" shows me the last copied item:
<img width="473" alt="Screenshot 2024-09-20 at 15 28 29" src="https://github.com/user-attachments/assets/346d17d6-e637-47cd-a118-f01de106ed90">

**Comment by p0deje** [comment] 2024-09-20 16:33
Can you show a screenshot of Maccy window resized to a bigger size?

**Comment by dbezic** [comment] 2024-09-20 17:21
This is the size with 200 chosen (it was 50 by default):
<img width="709" alt="Screenshot 2024-09-20 at 18 20 06" src="https://github.com/user-attachments/assets/17d4fce4-a823-4724-a032-e8ea4b4ec349"
<img width="451" alt="Screenshot 2024-09-20 at 18 20 46" src="https://github.com/user-attachments/assets/916a2353-724d-437d-b895-2a039a9021b7">
>

Something is not right here because the size even doesn't change

**Comment by dbezic** [comment] 2024-09-20 17:32
Manage to see the copied items, but the size still wouldn't update. Only when I hide the footer I am able to see the copied items

**Comment by p0deje** [comment] 2024-09-20 19:26
@dbezic You need to resize the Maccy popup. When it's shown, mouse over the bottom-right corner, click and hold the left mouse button, and drag the mouse to until it is of the size you prefer.

**Comment by dbezic** [comment] 2024-09-20 20:05
Yeah noticed that. But the actual fix for not copying items is because I had installed through brew and later through app store so it somehow messed things up. Reinstalling & cleaning all the files fixed the issue. Thanks for the support
