### ISSUE TITLE
Clicking Maccy Closes the Program

### ISSUE THREAD

**Issue by neoyanzong** [p0deje/Maccy#124] opened 2020-06-17 05:41 UTC
Hi there I have been using Maccy just fine for a while, but today Maccy just keeps closing when i click on it. Using the shortcut to access Maccy closes it too. 

Please assist!

Yan

Before Clicking:
![image](https://user-images.githubusercontent.com/67040554/84859694-3f364a80-b0a0-11ea-9959-a76009c302db.png)

After Clicking:
![image](https://user-images.githubusercontent.com/67040554/84859760-5aa15580-b0a0-11ea-8eee-179e9c04743d.png)

**Comment by TimGrell** [comment] 2020-06-17 10:57
I have the same problem

**Comment by p0deje** [comment] 2020-06-17 11:25
Duplicate of #123

**Closed by p0deje** 2020-06-17 11:25 UTC

**Comment by p0deje** [comment] 2020-06-17 11:45
Please upgrade to 0.12. In order to upgrade, either install from Github if you can't start Maccy or cleanup the history by removing `~/Library/Application Support/Maccy/Storage.sqlite` file - that should allow Maccy to start so you could upgrade.

**Comment by neoyanzong** [comment] 2020-06-17 14:19
Thank you so much,

It works now (:

Yan
