### ISSUE TITLE
Limit height of scrollable list

### ISSUE THREAD

**Issue by MatzeKitt** [p0deje/Maccy#680] opened 2023-11-22 08:49 UTC
If you set the amount of entries to 0, the list is scrollable. But it is only scrollable if the content doesn’t fit the whole screen. I would suggest to make the scrollable content height configurable so that you can e.g. set its height to 400px (or a fixed amount of entries) and if there are more entries, the content is scrollable from this point on.

This keeps the UI small and nice and also allows easier access of the fixed menu items für delete, settings, about and quit.

**Comment by p0deje** [comment] 2023-11-23 02:34
Duplicate of #229

**Closed by p0deje** 2023-11-23 02:34 UTC
