### ISSUE TITLE
Infinity copy history

### ISSUE THREAD

**Issue by skhaz** [p0deje/Maccy#952] opened 2024-11-14 14:56 UTC
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

It would be awesome if Maccy adds infinity copy history.

**Comment by p0deje** [comment] 2024-11-14 18:00
Duplicate of #310

**Closed by p0deje** 2024-11-14 18:00 UTC
Labels: enhancement
