### ISSUE TITLE
[V2] ⌥⌘⌫ does not clear copied items when footer is disabled

### ISSUE THREAD

**Issue by frankshrestha** [p0deje/Maccy#875] opened 2024-09-17 11:09 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0

### macOS Version

15.0 (24A335)

### Description

⌥⌘⌫ does not clear copied items when footer is disabled.

### Steps to Reproduce

- Copy few item to the clipboard.
- Open Maccy.
- Press ⌥⌘⌫.

**Comment by p0deje** [comment] 2024-09-17 14:55
Duplicate of #865

**Closed by p0deje** 2024-09-17 14:55 UTC
Labels: bug
