### ISSUE TITLE
Can't use maccy dropdown in fullscreen mode

### ISSUE THREAD

**Issue by Zmove** [p0deje/Maccy#769] opened 2024-04-21 10:13 UTC
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.30.0

### macOS Version

Sonoma 14.4.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":2048}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "514 422 585 380 0 0 1470 919 ";
    enabledPasteboardTypes =     (
        "public.file-url",
        "public.tiff",
        "public.png",
        "public.html",
        "public.utf8-plain-text",
        "public.rtf"
    );
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.typeit4me.clipping"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    numberOfUsages = 10;
    pasteByDefault = 1;
    popupPosition = cursor;
    suppressClearAlert = 1;
}
```

### Description

When an application is in fullscreen mode and you click on the maccy icon in the topbar, the maccy dropdown popup appear, but if you try to go down to a line in the clipboard history, the popup instantly disappear. See video below.

### Steps to Reproduce

1. Put something in you clipboard
2. Launch an app
3. Put the app in fullscreen
4. Try to reach the thing you put in your clipboard in your maccy history
You will see than you can't reach it, as soon as your cursor leave the topbar, the maccy dropdown popup disappear.

I precise that the popup works if I use the keyboard shortcut to display it, the problem only appears when I click on the maccy icon in the topbar to reach my clipboard history.

**Comment by p0deje** [comment] 2024-04-22 00:11
Duplicate of #637

**Closed by p0deje** 2024-04-22 00:11 UTC
Labels: bug
