### ISSUE TITLE
Feature Request: Searching by key-value

### ISSUE THREAD

**Issue by simonla** [p0deje/Maccy#214] opened 2020-11-27 03:33 UTC
User can add custom key-value pairs in setting

Such as <"mail","my_mai@gmail.com">
               <"phone"-"+861234567">

Then they can type key in serch bar and get value

This is more useful than pin

**Comment by p0deje** [comment] 2020-11-29 02:32
Duplicate of #89

**Closed by p0deje** 2020-11-29 02:32 UTC
