### ISSUE TITLE
History Size over 999 items

### ISSUE THREAD

**Issue by synox** [p0deje/Maccy#513] opened 2023-02-06 22:53 UTC
I need more than 999 items. The UI let's my type 10000, but does not persist it. 

<img width="422" alt="Screenshot 2023-02-06 at 14 53 01" src="https://user-images.githubusercontent.com/2250964/217105637-e93dcc65-8161-4b92-b07f-a081f7d9b76e.png">

**Comment by p0deje** [comment] 2023-02-08 15:19
Duplicate of #310

**Closed by p0deje** 2023-02-08 15:19 UTC
