### ISSUE TITLE
Searching for anything makes the app freeze since MacOS Sonoma 14.0 update

### ISSUE THREAD

**Issue by webdev69420** [p0deje/Maccy#648] opened 2023-10-18 14:21 UTC
Hi,

Since updating to MacOS Sonoma 14.0, everytime I search for something in the Maccy clipboard history, the app freezes (and I have to force quit the app and relaunch it) or crashes.

All other things work just fine (what I copy is captured by Maccy, I can paste anything in the history, etc.).

 There's nothing much to add. Maybe this can help?

- MacOS version: 14.0 (Sonoma)
- Maccy version: 0.27.1

**Comment by p0deje** [comment] 2023-10-18 22:27
Duplicate of #617

**Closed by p0deje** 2023-10-18 22:27 UTC
