### ISSUE TITLE
Limiting the number of items displayed

### ISSUE THREAD

**Issue by Axenntio** [p0deje/Maccy#396] opened 2022-05-05 15:28 UTC
When I open Maccy, I would like to see only like the 10 first element to avoid having all the height of my screen to be filled.

I only see one approach: limiting the number of returned items and taking search field in account, but this means that by using the arrow key I will not be able to manually search the 11th copied item. `(1)`

This arrow appears when the list is long enough to not fully fit on the screen height.
<img width="680" alt="Screenshot 2022-05-05 at 17 25 30" src="https://user-images.githubusercontent.com/18538043/166957775-25a8196c-e889-40c6-886f-8d5f344c3303.png">
I wonder if this is possible to have this behaviour by limiting the height of the list. `(2)`

Edit: See that this feature is implemented and editable via `Menu Size` preference and this is the approach `(1)`, so the point remain for the point `(2)`.

**Comment by p0deje** [comment] 2022-05-31 21:46
Duplicate of #229

**Closed by p0deje** 2022-05-31 21:46 UTC
